/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module axi_dwidth_converter_v2_1_b_downsizer(ARESET, ACLK, cmd_valid, cmd_split, cmd_repeat, cmd_ready, cmd_id, S_AXI_BID, S_AXI_BRESP, S_AXI_BVALID, S_AXI_BREADY, M_AXI_BRESP, M_AXI_BVALID, M_AXI_BREADY);
  wire [1:0] _000_;
  wire _001_;
  wire [7:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  input ACLK;
  input ARESET;
  output M_AXI_BREADY;
  wire M_AXI_BREADY_I;
  input [1:0] M_AXI_BRESP;
  input M_AXI_BVALID;
  output S_AXI_BID;
  wire S_AXI_BID_I;
  input S_AXI_BREADY;
  wire S_AXI_BREADY_I;
  output [1:0] S_AXI_BRESP;
  wire [1:0] S_AXI_BRESP_ACC;
  wire [1:0] S_AXI_BRESP_I;
  output S_AXI_BVALID;
  wire S_AXI_BVALID_I;
  input cmd_id;
  output cmd_ready;
  wire cmd_ready_i;
  input [7:0] cmd_repeat;
  input cmd_split;
  input cmd_valid;
  wire first_mi_word;
  wire [7:0] repeat_cnt;
  INV_X1 _078_ (
    .A(repeat_cnt[2]),
    .ZN(_023_)
  );
  INV_X1 _079_ (
    .A(repeat_cnt[3]),
    .ZN(_024_)
  );
  INV_X1 _080_ (
    .A(repeat_cnt[5]),
    .ZN(_025_)
  );
  INV_X1 _081_ (
    .A(repeat_cnt[6]),
    .ZN(_026_)
  );
  INV_X1 _082_ (
    .A(repeat_cnt[7]),
    .ZN(_027_)
  );
  INV_X1 _083_ (
    .A(ARESET),
    .ZN(_028_)
  );
  INV_X1 _084_ (
    .A(S_AXI_BRESP_ACC[0]),
    .ZN(_029_)
  );
  INV_X1 _085_ (
    .A(S_AXI_BRESP_ACC[1]),
    .ZN(_030_)
  );
  INV_X1 _086_ (
    .A(M_AXI_BRESP[1]),
    .ZN(_031_)
  );
  INV_X1 _087_ (
    .A(S_AXI_BREADY),
    .ZN(_032_)
  );
  NOR4_X1 _088_ (
    .A1(repeat_cnt[4]),
    .A2(repeat_cnt[5]),
    .A3(repeat_cnt[6]),
    .A4(repeat_cnt[7]),
    .ZN(_033_)
  );
  NOR4_X1 _089_ (
    .A1(repeat_cnt[0]),
    .A2(repeat_cnt[1]),
    .A3(repeat_cnt[2]),
    .A4(repeat_cnt[3]),
    .ZN(_034_)
  );
  AND4_X1 _090_ (
    .A1(_032_),
    .A2(_003_),
    .A3(_033_),
    .A4(_034_),
    .ZN(_035_)
  );
  NAND4_X1 _091_ (
    .A1(_032_),
    .A2(_003_),
    .A3(_033_),
    .A4(_034_),
    .ZN(_036_)
  );
  OR2_X1 _092_ (
    .A1(cmd_split),
    .A2(S_AXI_BREADY),
    .ZN(_037_)
  );
  AND2_X1 _093_ (
    .A1(M_AXI_BVALID),
    .A2(_037_),
    .ZN(_038_)
  );
  NAND2_X1 _094_ (
    .A1(M_AXI_BVALID),
    .A2(_037_),
    .ZN(_039_)
  );
  NOR2_X1 _095_ (
    .A1(_035_),
    .A2(_039_),
    .ZN(_040_)
  );
  NAND2_X1 _096_ (
    .A1(_036_),
    .A2(_038_),
    .ZN(_041_)
  );
  MUX2_X1 _097_ (
    .A(repeat_cnt[0]),
    .B(cmd_repeat[0]),
    .S(first_mi_word),
    .Z(_042_)
  );
  AOI21_X1 _098_ (
    .A(repeat_cnt[0]),
    .B1(_036_),
    .B2(_038_),
    .ZN(_043_)
  );
  AOI211_X1 _099_ (
    .A(ARESET),
    .B(_043_),
    .C1(_042_),
    .C2(_040_),
    .ZN(_002_[0])
  );
  MUX2_X1 _100_ (
    .A(repeat_cnt[1]),
    .B(cmd_repeat[1]),
    .S(first_mi_word),
    .Z(_044_)
  );
  XOR2_X1 _101_ (
    .A(_042_),
    .B(_044_),
    .Z(_045_)
  );
  AOI21_X1 _102_ (
    .A(repeat_cnt[1]),
    .B1(_036_),
    .B2(_038_),
    .ZN(_046_)
  );
  AOI211_X1 _103_ (
    .A(ARESET),
    .B(_046_),
    .C1(_045_),
    .C2(_040_),
    .ZN(_002_[1])
  );
  MUX2_X1 _104_ (
    .A(repeat_cnt[2]),
    .B(cmd_repeat[2]),
    .S(first_mi_word),
    .Z(_047_)
  );
  OR3_X1 _105_ (
    .A1(_042_),
    .A2(_044_),
    .A3(_047_),
    .ZN(_048_)
  );
  OAI21_X1 _106_ (
    .A(_047_),
    .B1(_044_),
    .B2(_042_),
    .ZN(_049_)
  );
  AND4_X1 _107_ (
    .A1(_036_),
    .A2(_038_),
    .A3(_048_),
    .A4(_049_),
    .ZN(_050_)
  );
  AOI211_X1 _108_ (
    .A(ARESET),
    .B(_050_),
    .C1(_041_),
    .C2(_023_),
    .ZN(_002_[2])
  );
  MUX2_X1 _109_ (
    .A(repeat_cnt[3]),
    .B(cmd_repeat[3]),
    .S(first_mi_word),
    .Z(_051_)
  );
  NOR4_X1 _110_ (
    .A1(_042_),
    .A2(_044_),
    .A3(_047_),
    .A4(_051_),
    .ZN(_052_)
  );
  OR4_X1 _111_ (
    .A1(_042_),
    .A2(_044_),
    .A3(_047_),
    .A4(_051_),
    .ZN(_053_)
  );
  AOI211_X1 _112_ (
    .A(_035_),
    .B(_039_),
    .C1(_048_),
    .C2(_051_),
    .ZN(_054_)
  );
  AOI221_X1 _113_ (
    .A(ARESET),
    .B1(_053_),
    .B2(_054_),
    .C1(_041_),
    .C2(_024_),
    .ZN(_002_[3])
  );
  MUX2_X1 _114_ (
    .A(repeat_cnt[4]),
    .B(cmd_repeat[4]),
    .S(first_mi_word),
    .Z(_055_)
  );
  XNOR2_X1 _115_ (
    .A(_052_),
    .B(_055_),
    .ZN(_056_)
  );
  AOI21_X1 _116_ (
    .A(repeat_cnt[4]),
    .B1(_036_),
    .B2(_038_),
    .ZN(_057_)
  );
  AOI211_X1 _117_ (
    .A(ARESET),
    .B(_057_),
    .C1(_056_),
    .C2(_040_),
    .ZN(_002_[4])
  );
  MUX2_X1 _118_ (
    .A(repeat_cnt[5]),
    .B(cmd_repeat[5]),
    .S(first_mi_word),
    .Z(_058_)
  );
  OAI21_X1 _119_ (
    .A(_058_),
    .B1(_055_),
    .B2(_053_),
    .ZN(_059_)
  );
  NOR2_X1 _120_ (
    .A1(_055_),
    .A2(_058_),
    .ZN(_060_)
  );
  OR2_X1 _121_ (
    .A1(_055_),
    .A2(_058_),
    .ZN(_061_)
  );
  AOI211_X1 _122_ (
    .A(_035_),
    .B(_039_),
    .C1(_052_),
    .C2(_060_),
    .ZN(_062_)
  );
  AOI221_X1 _123_ (
    .A(ARESET),
    .B1(_059_),
    .B2(_062_),
    .C1(_041_),
    .C2(_025_),
    .ZN(_002_[5])
  );
  MUX2_X1 _124_ (
    .A(repeat_cnt[6]),
    .B(cmd_repeat[6]),
    .S(first_mi_word),
    .Z(_063_)
  );
  OAI21_X1 _125_ (
    .A(_063_),
    .B1(_061_),
    .B2(_053_),
    .ZN(_064_)
  );
  NOR3_X1 _126_ (
    .A1(_055_),
    .A2(_058_),
    .A3(_063_),
    .ZN(_065_)
  );
  OR3_X1 _127_ (
    .A1(_055_),
    .A2(_058_),
    .A3(_063_),
    .ZN(_066_)
  );
  AOI211_X1 _128_ (
    .A(_035_),
    .B(_039_),
    .C1(_052_),
    .C2(_065_),
    .ZN(_067_)
  );
  AOI221_X1 _129_ (
    .A(ARESET),
    .B1(_064_),
    .B2(_067_),
    .C1(_041_),
    .C2(_026_),
    .ZN(_002_[6])
  );
  MUX2_X1 _130_ (
    .A(repeat_cnt[7]),
    .B(cmd_repeat[7]),
    .S(first_mi_word),
    .Z(_068_)
  );
  OAI21_X1 _131_ (
    .A(_068_),
    .B1(_066_),
    .B2(_053_),
    .ZN(_069_)
  );
  NOR4_X1 _132_ (
    .A1(_055_),
    .A2(_058_),
    .A3(_063_),
    .A4(_068_),
    .ZN(_006_)
  );
  AOI211_X1 _133_ (
    .A(_035_),
    .B(_039_),
    .C1(_052_),
    .C2(_006_),
    .ZN(_007_)
  );
  AOI221_X1 _134_ (
    .A(ARESET),
    .B1(_069_),
    .B2(_007_),
    .C1(_041_),
    .C2(_027_),
    .ZN(_002_[7])
  );
  AOI22_X1 _135_ (
    .A1(first_mi_word),
    .A2(cmd_split),
    .B1(M_AXI_BRESP[1]),
    .B2(_005_),
    .ZN(_008_)
  );
  OAI211_X1 _136_ (
    .A(M_AXI_BRESP[0]),
    .B(_004_),
    .C1(_005_),
    .C2(M_AXI_BRESP[1]),
    .ZN(_009_)
  );
  AOI21_X1 _137_ (
    .A(M_AXI_BRESP[0]),
    .B1(cmd_split),
    .B2(_008_),
    .ZN(_010_)
  );
  AND2_X1 _138_ (
    .A1(_008_),
    .A2(_009_),
    .ZN(_011_)
  );
  AND4_X1 _139_ (
    .A1(_029_),
    .A2(cmd_split),
    .A3(_008_),
    .A4(_009_),
    .ZN(_012_)
  );
  OR2_X1 _140_ (
    .A1(_010_),
    .A2(_012_),
    .ZN(_013_)
  );
  INV_X1 _141_ (
    .A(_013_),
    .ZN(S_AXI_BRESP[0])
  );
  AOI21_X1 _142_ (
    .A(S_AXI_BRESP_ACC[0]),
    .B1(_036_),
    .B2(_038_),
    .ZN(_014_)
  );
  AOI211_X1 _143_ (
    .A(ARESET),
    .B(_014_),
    .C1(_013_),
    .C2(_040_),
    .ZN(_000_[0])
  );
  NAND3_X1 _144_ (
    .A1(_030_),
    .A2(_008_),
    .A3(_009_),
    .ZN(_015_)
  );
  OAI211_X1 _145_ (
    .A(cmd_split),
    .B(_015_),
    .C1(_011_),
    .C2(M_AXI_BRESP[1]),
    .ZN(_016_)
  );
  NOR2_X1 _146_ (
    .A1(cmd_split),
    .A2(_031_),
    .ZN(_017_)
  );
  NOR3_X1 _147_ (
    .A1(_035_),
    .A2(_039_),
    .A3(_017_),
    .ZN(_018_)
  );
  AOI221_X1 _148_ (
    .A(ARESET),
    .B1(_030_),
    .B2(_041_),
    .C1(_016_),
    .C2(_018_),
    .ZN(_000_[1])
  );
  OAI21_X1 _149_ (
    .A(_016_),
    .B1(_031_),
    .B2(cmd_split),
    .ZN(S_AXI_BRESP[1])
  );
  NAND3_X1 _150_ (
    .A1(_003_),
    .A2(_033_),
    .A3(_034_),
    .ZN(_019_)
  );
  AND2_X1 _151_ (
    .A1(cmd_split),
    .A2(_019_),
    .ZN(_020_)
  );
  NAND2_X1 _152_ (
    .A1(cmd_split),
    .A2(_019_),
    .ZN(_021_)
  );
  NAND2_X1 _153_ (
    .A1(_032_),
    .A2(_021_),
    .ZN(M_AXI_BREADY)
  );
  AND2_X1 _154_ (
    .A1(M_AXI_BVALID),
    .A2(_021_),
    .ZN(S_AXI_BVALID)
  );
  AND3_X1 _155_ (
    .A1(cmd_valid),
    .A2(_040_),
    .A3(_021_),
    .ZN(cmd_ready)
  );
  OAI21_X1 _156_ (
    .A(first_mi_word),
    .B1(_035_),
    .B2(_039_),
    .ZN(_022_)
  );
  OAI211_X1 _157_ (
    .A(_028_),
    .B(_022_),
    .C1(_020_),
    .C2(_041_),
    .ZN(_001_)
  );
  DFF_X1 _158_ (
    .CK(ACLK),
    .D(_002_[0]),
    .Q(repeat_cnt[0]),
    .QN(_070_)
  );
  DFF_X1 _159_ (
    .CK(ACLK),
    .D(_002_[1]),
    .Q(repeat_cnt[1]),
    .QN(_071_)
  );
  DFF_X1 _160_ (
    .CK(ACLK),
    .D(_002_[2]),
    .Q(repeat_cnt[2]),
    .QN(_072_)
  );
  DFF_X1 _161_ (
    .CK(ACLK),
    .D(_002_[3]),
    .Q(repeat_cnt[3]),
    .QN(_073_)
  );
  DFF_X1 _162_ (
    .CK(ACLK),
    .D(_002_[4]),
    .Q(repeat_cnt[4]),
    .QN(_074_)
  );
  DFF_X1 _163_ (
    .CK(ACLK),
    .D(_002_[5]),
    .Q(repeat_cnt[5]),
    .QN(_075_)
  );
  DFF_X1 _164_ (
    .CK(ACLK),
    .D(_002_[6]),
    .Q(repeat_cnt[6]),
    .QN(_076_)
  );
  DFF_X1 _165_ (
    .CK(ACLK),
    .D(_002_[7]),
    .Q(repeat_cnt[7]),
    .QN(_077_)
  );
  DFF_X1 _166_ (
    .CK(ACLK),
    .D(_001_),
    .Q(first_mi_word),
    .QN(_003_)
  );
  DFF_X1 _167_ (
    .CK(ACLK),
    .D(_000_[0]),
    .Q(S_AXI_BRESP_ACC[0]),
    .QN(_004_)
  );
  DFF_X1 _168_ (
    .CK(ACLK),
    .D(_000_[1]),
    .Q(S_AXI_BRESP_ACC[1]),
    .QN(_005_)
  );
  assign M_AXI_BREADY_I = M_AXI_BREADY;
  assign S_AXI_BID = cmd_id;
  assign S_AXI_BID_I = cmd_id;
  assign S_AXI_BREADY_I = S_AXI_BREADY;
  assign S_AXI_BRESP_I = S_AXI_BRESP;
  assign S_AXI_BVALID_I = S_AXI_BVALID;
  assign cmd_ready_i = cmd_ready;
endmodule
