/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module top(\totalcoeffs[0] , \totalcoeffs[1] , \totalcoeffs[2] , \totalcoeffs[3] , \totalcoeffs[4] , \ctable[0] , \ctable[1] , \ctable[2] , \trailingones[0] , \trailingones[1] , \coeff_token[0] , \coeff_token[1] , \coeff_token[2] , \coeff_token[3] , \coeff_token[4] , \coeff_token[5] , \ctoken_len[0] , \ctoken_len[1] , \ctoken_len[2] , \ctoken_len[3] , \ctoken_len[4] );
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  output \coeff_token[0] ;
  output \coeff_token[1] ;
  output \coeff_token[2] ;
  output \coeff_token[3] ;
  output \coeff_token[4] ;
  output \coeff_token[5] ;
  input \ctable[0] ;
  input \ctable[1] ;
  input \ctable[2] ;
  output \ctoken_len[0] ;
  output \ctoken_len[1] ;
  output \ctoken_len[2] ;
  output \ctoken_len[3] ;
  output \ctoken_len[4] ;
  input \totalcoeffs[0] ;
  input \totalcoeffs[1] ;
  input \totalcoeffs[2] ;
  input \totalcoeffs[3] ;
  input \totalcoeffs[4] ;
  input \trailingones[0] ;
  input \trailingones[1] ;
  INV_X1 _372_ (
    .A(\ctable[0] ),
    .ZN(_128_)
  );
  INV_X1 _373_ (
    .A(\ctable[2] ),
    .ZN(_139_)
  );
  INV_X1 _374_ (
    .A(\trailingones[1] ),
    .ZN(_149_)
  );
  INV_X1 _375_ (
    .A(\totalcoeffs[2] ),
    .ZN(_160_)
  );
  INV_X1 _376_ (
    .A(\totalcoeffs[0] ),
    .ZN(_171_)
  );
  INV_X1 _377_ (
    .A(\totalcoeffs[1] ),
    .ZN(_180_)
  );
  INV_X1 _378_ (
    .A(\totalcoeffs[3] ),
    .ZN(_190_)
  );
  INV_X1 _379_ (
    .A(\ctable[1] ),
    .ZN(_201_)
  );
  INV_X1 _380_ (
    .A(\trailingones[0] ),
    .ZN(_212_)
  );
  INV_X1 _381_ (
    .A(\totalcoeffs[4] ),
    .ZN(_222_)
  );
  NAND2_X1 _382_ (
    .A1(_128_),
    .A2(_212_),
    .ZN(_233_)
  );
  NOR2_X1 _383_ (
    .A1(_149_),
    .A2(_160_),
    .ZN(_244_)
  );
  NAND2_X1 _384_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[2] ),
    .ZN(_255_)
  );
  NOR2_X1 _385_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[1] ),
    .ZN(_265_)
  );
  OR2_X1 _386_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[1] ),
    .ZN(_276_)
  );
  NAND2_X1 _387_ (
    .A1(\totalcoeffs[2] ),
    .A2(\totalcoeffs[3] ),
    .ZN(_287_)
  );
  AOI21_X1 _388_ (
    .A(_276_),
    .B1(_201_),
    .B2(\totalcoeffs[3] ),
    .ZN(_297_)
  );
  AOI21_X1 _389_ (
    .A(_244_),
    .B1(_287_),
    .B2(_297_),
    .ZN(_307_)
  );
  NOR2_X1 _390_ (
    .A1(_180_),
    .A2(\trailingones[0] ),
    .ZN(_312_)
  );
  NOR2_X1 _391_ (
    .A1(_160_),
    .A2(\totalcoeffs[1] ),
    .ZN(_313_)
  );
  NOR2_X1 _392_ (
    .A1(_149_),
    .A2(\totalcoeffs[3] ),
    .ZN(_314_)
  );
  NOR2_X1 _393_ (
    .A1(_149_),
    .A2(\totalcoeffs[1] ),
    .ZN(_315_)
  );
  NAND2_X1 _394_ (
    .A1(\trailingones[1] ),
    .A2(_180_),
    .ZN(_316_)
  );
  NOR2_X1 _395_ (
    .A1(_160_),
    .A2(\totalcoeffs[3] ),
    .ZN(_317_)
  );
  NOR3_X1 _396_ (
    .A1(\totalcoeffs[1] ),
    .A2(\totalcoeffs[3] ),
    .A3(_255_),
    .ZN(_318_)
  );
  OAI211_X1 _397_ (
    .A(_128_),
    .B(_171_),
    .C1(_312_),
    .C2(_318_),
    .ZN(_319_)
  );
  NOR2_X1 _398_ (
    .A1(\trailingones[1] ),
    .A2(\trailingones[0] ),
    .ZN(_320_)
  );
  OR2_X1 _399_ (
    .A1(\trailingones[1] ),
    .A2(\trailingones[0] ),
    .ZN(_321_)
  );
  NOR2_X1 _400_ (
    .A1(\totalcoeffs[1] ),
    .A2(_321_),
    .ZN(_322_)
  );
  NOR2_X1 _401_ (
    .A1(\totalcoeffs[2] ),
    .A2(\totalcoeffs[0] ),
    .ZN(_323_)
  );
  OR2_X1 _402_ (
    .A1(\totalcoeffs[2] ),
    .A2(\totalcoeffs[0] ),
    .ZN(_324_)
  );
  NOR2_X1 _403_ (
    .A1(\totalcoeffs[2] ),
    .A2(\totalcoeffs[3] ),
    .ZN(_325_)
  );
  OR2_X1 _404_ (
    .A1(\totalcoeffs[2] ),
    .A2(\totalcoeffs[3] ),
    .ZN(_326_)
  );
  NAND3_X1 _405_ (
    .A1(_171_),
    .A2(_322_),
    .A3(_325_),
    .ZN(_327_)
  );
  OAI211_X1 _406_ (
    .A(_319_),
    .B(_327_),
    .C1(_233_),
    .C2(_307_),
    .ZN(_328_)
  );
  NOR2_X1 _407_ (
    .A1(\trailingones[1] ),
    .A2(_171_),
    .ZN(_329_)
  );
  NAND2_X1 _408_ (
    .A1(_149_),
    .A2(\totalcoeffs[0] ),
    .ZN(_330_)
  );
  NOR2_X1 _409_ (
    .A1(\totalcoeffs[0] ),
    .A2(\trailingones[0] ),
    .ZN(_331_)
  );
  AOI221_X1 _410_ (
    .A(_312_),
    .B1(_313_),
    .B2(_329_),
    .C1(_331_),
    .C2(\trailingones[1] ),
    .ZN(_332_)
  );
  NAND2_X1 _411_ (
    .A1(_128_),
    .A2(\totalcoeffs[3] ),
    .ZN(_333_)
  );
  NOR2_X1 _412_ (
    .A1(\trailingones[1] ),
    .A2(_180_),
    .ZN(_334_)
  );
  NOR2_X1 _413_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[2] ),
    .ZN(_335_)
  );
  OR2_X1 _414_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[2] ),
    .ZN(_336_)
  );
  NOR2_X1 _415_ (
    .A1(_180_),
    .A2(_336_),
    .ZN(_337_)
  );
  NOR2_X1 _416_ (
    .A1(\totalcoeffs[0] ),
    .A2(\totalcoeffs[3] ),
    .ZN(_338_)
  );
  NAND2_X1 _417_ (
    .A1(_149_),
    .A2(\totalcoeffs[2] ),
    .ZN(_339_)
  );
  XOR2_X1 _418_ (
    .A(\trailingones[1] ),
    .B(\totalcoeffs[2] ),
    .Z(_340_)
  );
  OAI211_X1 _419_ (
    .A(\ctable[1] ),
    .B(_338_),
    .C1(_337_),
    .C2(_244_),
    .ZN(_341_)
  );
  XNOR2_X1 _420_ (
    .A(\trailingones[1] ),
    .B(\totalcoeffs[0] ),
    .ZN(_342_)
  );
  NAND2_X1 _421_ (
    .A1(\ctable[0] ),
    .A2(\totalcoeffs[1] ),
    .ZN(_343_)
  );
  NOR2_X1 _422_ (
    .A1(_180_),
    .A2(\totalcoeffs[3] ),
    .ZN(_344_)
  );
  NOR2_X1 _423_ (
    .A1(_326_),
    .A2(_343_),
    .ZN(_345_)
  );
  NAND2_X1 _424_ (
    .A1(\ctable[0] ),
    .A2(\ctable[1] ),
    .ZN(_346_)
  );
  AOI211_X1 _425_ (
    .A(_323_),
    .B(_346_),
    .C1(\trailingones[1] ),
    .C2(_160_),
    .ZN(_347_)
  );
  AOI21_X1 _426_ (
    .A(_347_),
    .B1(_345_),
    .B2(_342_),
    .ZN(_348_)
  );
  AOI21_X1 _427_ (
    .A(_212_),
    .B1(_341_),
    .B2(_348_),
    .ZN(_349_)
  );
  NOR2_X1 _428_ (
    .A1(\totalcoeffs[0] ),
    .A2(\totalcoeffs[1] ),
    .ZN(_350_)
  );
  AOI21_X1 _429_ (
    .A(\ctable[0] ),
    .B1(_315_),
    .B2(_323_),
    .ZN(_351_)
  );
  NAND2_X1 _430_ (
    .A1(\ctable[1] ),
    .A2(\trailingones[0] ),
    .ZN(_352_)
  );
  NAND2_X1 _431_ (
    .A1(\ctable[0] ),
    .A2(\trailingones[0] ),
    .ZN(_353_)
  );
  AND2_X1 _432_ (
    .A1(\totalcoeffs[2] ),
    .A2(\totalcoeffs[1] ),
    .ZN(_354_)
  );
  NAND2_X1 _433_ (
    .A1(\totalcoeffs[2] ),
    .A2(\totalcoeffs[1] ),
    .ZN(_355_)
  );
  NAND4_X1 _434_ (
    .A1(\ctable[0] ),
    .A2(\trailingones[0] ),
    .A3(_342_),
    .A4(_354_),
    .ZN(_356_)
  );
  OAI221_X1 _435_ (
    .A(_356_),
    .B1(_352_),
    .B2(_351_),
    .C1(\ctable[0] ),
    .C2(_332_),
    .ZN(_357_)
  );
  AOI211_X1 _436_ (
    .A(_328_),
    .B(_349_),
    .C1(_357_),
    .C2(\totalcoeffs[3] ),
    .ZN(_358_)
  );
  NOR2_X1 _437_ (
    .A1(\ctable[2] ),
    .A2(\totalcoeffs[4] ),
    .ZN(_359_)
  );
  NAND2_X1 _438_ (
    .A1(_139_),
    .A2(_222_),
    .ZN(_360_)
  );
  NOR2_X1 _439_ (
    .A1(\ctable[1] ),
    .A2(\totalcoeffs[4] ),
    .ZN(_361_)
  );
  NOR2_X1 _440_ (
    .A1(\ctable[0] ),
    .A2(\trailingones[1] ),
    .ZN(_362_)
  );
  OR2_X1 _441_ (
    .A1(\ctable[0] ),
    .A2(\trailingones[1] ),
    .ZN(_363_)
  );
  AOI21_X1 _442_ (
    .A(_363_),
    .B1(\totalcoeffs[1] ),
    .B2(_139_),
    .ZN(_364_)
  );
  NAND2_X1 _443_ (
    .A1(\ctable[2] ),
    .A2(\trailingones[0] ),
    .ZN(_365_)
  );
  NOR2_X1 _444_ (
    .A1(\ctable[0] ),
    .A2(_365_),
    .ZN(_366_)
  );
  OAI22_X1 _445_ (
    .A1(\ctable[2] ),
    .A2(_149_),
    .B1(_365_),
    .B2(\ctable[0] ),
    .ZN(_367_)
  );
  AND3_X1 _446_ (
    .A1(_149_),
    .A2(\totalcoeffs[2] ),
    .A3(_350_),
    .ZN(_368_)
  );
  AOI21_X1 _447_ (
    .A(_364_),
    .B1(_367_),
    .B2(\totalcoeffs[1] ),
    .ZN(_369_)
  );
  NOR2_X1 _448_ (
    .A1(\totalcoeffs[2] ),
    .A2(_171_),
    .ZN(_370_)
  );
  AOI21_X1 _449_ (
    .A(_370_),
    .B1(_368_),
    .B2(_366_),
    .ZN(_371_)
  );
  NOR3_X1 _450_ (
    .A1(_149_),
    .A2(\totalcoeffs[1] ),
    .A3(_325_),
    .ZN(_000_)
  );
  NOR2_X1 _451_ (
    .A1(\ctable[0] ),
    .A2(\totalcoeffs[2] ),
    .ZN(_001_)
  );
  NOR3_X1 _452_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[0] ),
    .A3(_001_),
    .ZN(_002_)
  );
  NAND2_X1 _453_ (
    .A1(\totalcoeffs[0] ),
    .A2(\totalcoeffs[3] ),
    .ZN(_003_)
  );
  OAI22_X1 _454_ (
    .A1(\trailingones[1] ),
    .A2(_355_),
    .B1(_003_),
    .B2(\totalcoeffs[1] ),
    .ZN(_004_)
  );
  NOR2_X1 _455_ (
    .A1(_160_),
    .A2(\totalcoeffs[0] ),
    .ZN(_005_)
  );
  NOR4_X1 _456_ (
    .A1(_344_),
    .A2(_000_),
    .A3(_002_),
    .A4(_004_),
    .ZN(_006_)
  );
  OAI33_X1 _457_ (
    .A1(\totalcoeffs[3] ),
    .A2(_369_),
    .A3(_371_),
    .B1(_006_),
    .B2(\trailingones[0] ),
    .B3(\ctable[2] ),
    .ZN(_007_)
  );
  NOR2_X1 _458_ (
    .A1(\trailingones[1] ),
    .A2(\ctable[1] ),
    .ZN(_008_)
  );
  OR2_X1 _459_ (
    .A1(\trailingones[1] ),
    .A2(\ctable[1] ),
    .ZN(_009_)
  );
  AOI21_X1 _460_ (
    .A(_008_),
    .B1(\totalcoeffs[4] ),
    .B2(\trailingones[0] ),
    .ZN(_010_)
  );
  NAND2_X1 _461_ (
    .A1(_201_),
    .A2(\trailingones[0] ),
    .ZN(_011_)
  );
  NOR2_X1 _462_ (
    .A1(_128_),
    .A2(\trailingones[0] ),
    .ZN(_012_)
  );
  NAND2_X1 _463_ (
    .A1(\ctable[0] ),
    .A2(_011_),
    .ZN(_013_)
  );
  NOR2_X1 _464_ (
    .A1(\ctable[1] ),
    .A2(\trailingones[0] ),
    .ZN(_014_)
  );
  NAND2_X1 _465_ (
    .A1(_201_),
    .A2(_320_),
    .ZN(_015_)
  );
  OAI211_X1 _466_ (
    .A(_346_),
    .B(_009_),
    .C1(_149_),
    .C2(\totalcoeffs[4] ),
    .ZN(_016_)
  );
  OAI22_X1 _467_ (
    .A1(_010_),
    .A2(_013_),
    .B1(_016_),
    .B2(\trailingones[0] ),
    .ZN(_017_)
  );
  NOR2_X1 _468_ (
    .A1(\totalcoeffs[1] ),
    .A2(_326_),
    .ZN(_018_)
  );
  NAND2_X1 _469_ (
    .A1(_139_),
    .A2(_171_),
    .ZN(_019_)
  );
  NOR3_X1 _470_ (
    .A1(\totalcoeffs[1] ),
    .A2(_326_),
    .A3(_019_),
    .ZN(_020_)
  );
  NOR2_X1 _471_ (
    .A1(\ctable[0] ),
    .A2(\totalcoeffs[3] ),
    .ZN(_021_)
  );
  NAND2_X1 _472_ (
    .A1(\totalcoeffs[0] ),
    .A2(\totalcoeffs[1] ),
    .ZN(_022_)
  );
  NAND2_X1 _473_ (
    .A1(_021_),
    .A2(_022_),
    .ZN(_023_)
  );
  OAI21_X1 _474_ (
    .A(_023_),
    .B1(_350_),
    .B2(\ctable[2] ),
    .ZN(_024_)
  );
  AND2_X1 _475_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[1] ),
    .ZN(_025_)
  );
  NAND2_X1 _476_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[1] ),
    .ZN(_026_)
  );
  NAND2_X1 _477_ (
    .A1(_276_),
    .A2(_026_),
    .ZN(_027_)
  );
  NOR2_X1 _478_ (
    .A1(\totalcoeffs[2] ),
    .A2(\trailingones[0] ),
    .ZN(_028_)
  );
  AND4_X1 _479_ (
    .A1(_361_),
    .A2(_024_),
    .A3(_027_),
    .A4(_028_),
    .ZN(_029_)
  );
  AOI221_X1 _480_ (
    .A(_029_),
    .B1(_020_),
    .B2(_017_),
    .C1(_361_),
    .C2(_007_),
    .ZN(_030_)
  );
  OAI21_X1 _481_ (
    .A(_030_),
    .B1(_360_),
    .B2(_358_),
    .ZN(\coeff_token[0] )
  );
  NOR2_X1 _482_ (
    .A1(_149_),
    .A2(_201_),
    .ZN(_031_)
  );
  NAND2_X1 _483_ (
    .A1(\trailingones[1] ),
    .A2(\ctable[1] ),
    .ZN(_032_)
  );
  OAI21_X1 _484_ (
    .A(_032_),
    .B1(_212_),
    .B2(\ctable[0] ),
    .ZN(_033_)
  );
  NOR2_X1 _485_ (
    .A1(\trailingones[0] ),
    .A2(_363_),
    .ZN(_034_)
  );
  AOI221_X1 _486_ (
    .A(_034_),
    .B1(_031_),
    .B2(\trailingones[0] ),
    .C1(_171_),
    .C2(_033_),
    .ZN(_035_)
  );
  NOR2_X1 _487_ (
    .A1(_160_),
    .A2(\totalcoeffs[4] ),
    .ZN(_036_)
  );
  INV_X1 _488_ (
    .A(_036_),
    .ZN(_037_)
  );
  AOI21_X1 _489_ (
    .A(_012_),
    .B1(_321_),
    .B2(\totalcoeffs[4] ),
    .ZN(_038_)
  );
  OAI221_X1 _490_ (
    .A(_323_),
    .B1(_008_),
    .B2(_031_),
    .C1(\totalcoeffs[4] ),
    .C2(_201_),
    .ZN(_039_)
  );
  NOR2_X1 _491_ (
    .A1(_171_),
    .A2(_212_),
    .ZN(_040_)
  );
  NAND2_X1 _492_ (
    .A1(\totalcoeffs[0] ),
    .A2(\trailingones[0] ),
    .ZN(_041_)
  );
  OAI22_X1 _493_ (
    .A1(_321_),
    .A2(_324_),
    .B1(_041_),
    .B2(_255_),
    .ZN(_042_)
  );
  NAND3_X1 _494_ (
    .A1(\ctable[0] ),
    .A2(_222_),
    .A3(_042_),
    .ZN(_043_)
  );
  OAI221_X1 _495_ (
    .A(_043_),
    .B1(_039_),
    .B2(_038_),
    .C1(_035_),
    .C2(_037_),
    .ZN(_044_)
  );
  NAND3_X1 _496_ (
    .A1(_352_),
    .A2(_370_),
    .A3(_033_),
    .ZN(_045_)
  );
  OAI21_X1 _497_ (
    .A(_160_),
    .B1(\totalcoeffs[0] ),
    .B2(_201_),
    .ZN(_046_)
  );
  NAND3_X1 _498_ (
    .A1(\trailingones[0] ),
    .A2(_362_),
    .A3(_046_),
    .ZN(_047_)
  );
  NAND4_X1 _499_ (
    .A1(\ctable[0] ),
    .A2(\trailingones[1] ),
    .A3(_160_),
    .A4(_331_),
    .ZN(_048_)
  );
  NAND4_X1 _500_ (
    .A1(_015_),
    .A2(_045_),
    .A3(_047_),
    .A4(_048_),
    .ZN(_049_)
  );
  NOR2_X1 _501_ (
    .A1(_180_),
    .A2(\totalcoeffs[4] ),
    .ZN(_050_)
  );
  NOR3_X1 _502_ (
    .A1(\totalcoeffs[4] ),
    .A2(_339_),
    .A3(_011_),
    .ZN(_051_)
  );
  AOI221_X1 _503_ (
    .A(_051_),
    .B1(_050_),
    .B2(_049_),
    .C1(_180_),
    .C2(_044_),
    .ZN(_052_)
  );
  NAND2_X1 _504_ (
    .A1(_139_),
    .A2(_190_),
    .ZN(_053_)
  );
  OR2_X1 _505_ (
    .A1(\ctable[0] ),
    .A2(\ctable[1] ),
    .ZN(_054_)
  );
  NAND2_X1 _506_ (
    .A1(_361_),
    .A2(_021_),
    .ZN(_055_)
  );
  INV_X1 _507_ (
    .A(_055_),
    .ZN(_056_)
  );
  NAND3_X1 _508_ (
    .A1(_160_),
    .A2(_330_),
    .A3(_022_),
    .ZN(_057_)
  );
  OAI21_X1 _509_ (
    .A(\totalcoeffs[2] ),
    .B1(\totalcoeffs[0] ),
    .B2(\totalcoeffs[1] ),
    .ZN(_058_)
  );
  AND4_X1 _510_ (
    .A1(\ctable[2] ),
    .A2(_212_),
    .A3(_057_),
    .A4(_058_),
    .ZN(_059_)
  );
  NAND2_X1 _511_ (
    .A1(\trailingones[0] ),
    .A2(_334_),
    .ZN(_060_)
  );
  NAND2_X1 _512_ (
    .A1(\ctable[2] ),
    .A2(_160_),
    .ZN(_061_)
  );
  NOR2_X1 _513_ (
    .A1(_060_),
    .A2(_061_),
    .ZN(_062_)
  );
  NOR3_X1 _514_ (
    .A1(_368_),
    .A2(_059_),
    .A3(_062_),
    .ZN(_063_)
  );
  NOR2_X1 _515_ (
    .A1(\totalcoeffs[3] ),
    .A2(\trailingones[0] ),
    .ZN(_064_)
  );
  NOR2_X1 _516_ (
    .A1(_190_),
    .A2(\trailingones[0] ),
    .ZN(_065_)
  );
  OAI21_X1 _517_ (
    .A(_353_),
    .B1(\trailingones[0] ),
    .B2(_190_),
    .ZN(_066_)
  );
  NOR2_X1 _518_ (
    .A1(\totalcoeffs[1] ),
    .A2(\ctable[1] ),
    .ZN(_067_)
  );
  NAND3_X1 _519_ (
    .A1(\totalcoeffs[0] ),
    .A2(_066_),
    .A3(_067_),
    .ZN(_068_)
  );
  NOR2_X1 _520_ (
    .A1(\totalcoeffs[0] ),
    .A2(_212_),
    .ZN(_069_)
  );
  NAND2_X1 _521_ (
    .A1(_171_),
    .A2(\trailingones[0] ),
    .ZN(_070_)
  );
  AOI21_X1 _522_ (
    .A(_067_),
    .B1(\trailingones[0] ),
    .B2(_171_),
    .ZN(_071_)
  );
  NAND3_X1 _523_ (
    .A1(_001_),
    .A2(_022_),
    .A3(_071_),
    .ZN(_072_)
  );
  NAND2_X1 _524_ (
    .A1(_068_),
    .A2(_072_),
    .ZN(_073_)
  );
  OR2_X1 _525_ (
    .A1(\totalcoeffs[1] ),
    .A2(\trailingones[0] ),
    .ZN(_074_)
  );
  OAI21_X1 _526_ (
    .A(_074_),
    .B1(\ctable[1] ),
    .B2(_160_),
    .ZN(_075_)
  );
  NOR2_X1 _527_ (
    .A1(\totalcoeffs[0] ),
    .A2(\ctable[1] ),
    .ZN(_076_)
  );
  AOI21_X1 _528_ (
    .A(\totalcoeffs[2] ),
    .B1(\totalcoeffs[3] ),
    .B2(\trailingones[0] ),
    .ZN(_077_)
  );
  OAI33_X1 _529_ (
    .A1(_333_),
    .A2(_354_),
    .A3(_075_),
    .B1(_077_),
    .B2(\totalcoeffs[0] ),
    .B3(\ctable[1] ),
    .ZN(_078_)
  );
  NAND2_X1 _530_ (
    .A1(_128_),
    .A2(\totalcoeffs[0] ),
    .ZN(_079_)
  );
  XNOR2_X1 _531_ (
    .A(\ctable[0] ),
    .B(\totalcoeffs[0] ),
    .ZN(_080_)
  );
  OAI21_X1 _532_ (
    .A(_080_),
    .B1(_041_),
    .B2(\totalcoeffs[2] ),
    .ZN(_081_)
  );
  NAND3_X1 _533_ (
    .A1(\totalcoeffs[1] ),
    .A2(_201_),
    .A3(_081_),
    .ZN(_082_)
  );
  NAND3_X1 _534_ (
    .A1(\ctable[0] ),
    .A2(_028_),
    .A3(_067_),
    .ZN(_083_)
  );
  NAND3_X1 _535_ (
    .A1(_149_),
    .A2(_082_),
    .A3(_083_),
    .ZN(_084_)
  );
  NOR3_X1 _536_ (
    .A1(_073_),
    .A2(_078_),
    .A3(_084_),
    .ZN(_085_)
  );
  NAND2_X1 _537_ (
    .A1(_160_),
    .A2(\totalcoeffs[3] ),
    .ZN(_086_)
  );
  OAI21_X1 _538_ (
    .A(_343_),
    .B1(_074_),
    .B2(_086_),
    .ZN(_087_)
  );
  AND3_X1 _539_ (
    .A1(\totalcoeffs[0] ),
    .A2(\ctable[1] ),
    .A3(_087_),
    .ZN(_088_)
  );
  OAI211_X1 _540_ (
    .A(\totalcoeffs[3] ),
    .B(_354_),
    .C1(_012_),
    .C2(\ctable[1] ),
    .ZN(_089_)
  );
  OAI211_X1 _541_ (
    .A(\trailingones[1] ),
    .B(_089_),
    .C1(_346_),
    .C2(_325_),
    .ZN(_090_)
  );
  OAI21_X1 _542_ (
    .A(_359_),
    .B1(_088_),
    .B2(_090_),
    .ZN(_091_)
  );
  OAI222_X1 _543_ (
    .A1(_052_),
    .A2(_053_),
    .B1(_055_),
    .B2(_063_),
    .C1(_085_),
    .C2(_091_),
    .ZN(\coeff_token[1] )
  );
  NAND2_X1 _544_ (
    .A1(\trailingones[1] ),
    .A2(\trailingones[0] ),
    .ZN(_092_)
  );
  INV_X1 _545_ (
    .A(_092_),
    .ZN(_093_)
  );
  NOR2_X1 _546_ (
    .A1(_171_),
    .A2(_092_),
    .ZN(_094_)
  );
  NAND2_X1 _547_ (
    .A1(\ctable[0] ),
    .A2(_321_),
    .ZN(_095_)
  );
  OAI221_X1 _548_ (
    .A(\totalcoeffs[1] ),
    .B1(_094_),
    .B2(_095_),
    .C1(_244_),
    .C2(\ctable[0] ),
    .ZN(_096_)
  );
  AND2_X1 _549_ (
    .A1(_321_),
    .A2(_092_),
    .ZN(_097_)
  );
  OAI21_X1 _550_ (
    .A(\totalcoeffs[2] ),
    .B1(_265_),
    .B2(_097_),
    .ZN(_098_)
  );
  AOI211_X1 _551_ (
    .A(\totalcoeffs[3] ),
    .B(\ctable[1] ),
    .C1(_096_),
    .C2(_098_),
    .ZN(_099_)
  );
  NAND4_X1 _552_ (
    .A1(\trailingones[1] ),
    .A2(_180_),
    .A3(\trailingones[0] ),
    .A4(_326_),
    .ZN(_100_)
  );
  OAI21_X1 _553_ (
    .A(\ctable[0] ),
    .B1(\totalcoeffs[1] ),
    .B2(_190_),
    .ZN(_101_)
  );
  NAND3_X1 _554_ (
    .A1(_160_),
    .A2(_320_),
    .A3(_101_),
    .ZN(_102_)
  );
  AOI211_X1 _555_ (
    .A(_171_),
    .B(\ctable[1] ),
    .C1(_100_),
    .C2(_102_),
    .ZN(_103_)
  );
  OAI21_X1 _556_ (
    .A(_359_),
    .B1(_099_),
    .B2(_103_),
    .ZN(_104_)
  );
  NOR2_X1 _557_ (
    .A1(_201_),
    .A2(\trailingones[0] ),
    .ZN(_105_)
  );
  AOI211_X1 _558_ (
    .A(\ctable[0] ),
    .B(_014_),
    .C1(\trailingones[0] ),
    .C2(_149_),
    .ZN(_106_)
  );
  OR4_X1 _559_ (
    .A1(\totalcoeffs[1] ),
    .A2(_222_),
    .A3(_326_),
    .A4(_106_),
    .ZN(_107_)
  );
  NOR2_X1 _560_ (
    .A1(\totalcoeffs[3] ),
    .A2(_026_),
    .ZN(_108_)
  );
  AOI22_X1 _561_ (
    .A1(_315_),
    .A2(_065_),
    .B1(_105_),
    .B2(_108_),
    .ZN(_109_)
  );
  NAND2_X1 _562_ (
    .A1(_128_),
    .A2(\totalcoeffs[2] ),
    .ZN(_110_)
  );
  OAI21_X1 _563_ (
    .A(\totalcoeffs[3] ),
    .B1(_160_),
    .B2(\ctable[0] ),
    .ZN(_111_)
  );
  NAND3_X1 _564_ (
    .A1(\trailingones[0] ),
    .A2(_334_),
    .A3(_111_),
    .ZN(_112_)
  );
  NAND3_X1 _565_ (
    .A1(\ctable[0] ),
    .A2(\totalcoeffs[2] ),
    .A3(_011_),
    .ZN(_113_)
  );
  NAND4_X1 _566_ (
    .A1(_107_),
    .A2(_109_),
    .A3(_112_),
    .A4(_113_),
    .ZN(_114_)
  );
  NOR2_X1 _567_ (
    .A1(\ctable[0] ),
    .A2(_201_),
    .ZN(_115_)
  );
  NAND2_X1 _568_ (
    .A1(_128_),
    .A2(\ctable[1] ),
    .ZN(_116_)
  );
  NAND2_X1 _569_ (
    .A1(\ctable[1] ),
    .A2(_021_),
    .ZN(_117_)
  );
  AOI21_X1 _570_ (
    .A(_190_),
    .B1(\trailingones[0] ),
    .B2(_160_),
    .ZN(_118_)
  );
  NAND3_X1 _571_ (
    .A1(_149_),
    .A2(_180_),
    .A3(_190_),
    .ZN(_119_)
  );
  OAI33_X1 _572_ (
    .A1(\trailingones[1] ),
    .A2(_343_),
    .A3(_118_),
    .B1(_119_),
    .B2(_116_),
    .B3(\trailingones[0] ),
    .ZN(_120_)
  );
  AOI211_X1 _573_ (
    .A(_008_),
    .B(_086_),
    .C1(\trailingones[0] ),
    .C2(_334_),
    .ZN(_121_)
  );
  AOI21_X1 _574_ (
    .A(_344_),
    .B1(_212_),
    .B2(\trailingones[1] ),
    .ZN(_122_)
  );
  OAI33_X1 _575_ (
    .A1(_128_),
    .A2(\totalcoeffs[1] ),
    .A3(_077_),
    .B1(_122_),
    .B2(\ctable[1] ),
    .B3(_314_),
    .ZN(_123_)
  );
  NOR4_X1 _576_ (
    .A1(_114_),
    .A2(_120_),
    .A3(_121_),
    .A4(_123_),
    .ZN(_124_)
  );
  AOI21_X1 _577_ (
    .A(_019_),
    .B1(_107_),
    .B2(\totalcoeffs[4] ),
    .ZN(_125_)
  );
  INV_X1 _578_ (
    .A(_125_),
    .ZN(_126_)
  );
  NOR3_X1 _579_ (
    .A1(\totalcoeffs[1] ),
    .A2(_201_),
    .A3(_212_),
    .ZN(_127_)
  );
  OAI22_X1 _580_ (
    .A1(_160_),
    .A2(_321_),
    .B1(_355_),
    .B2(_032_),
    .ZN(_129_)
  );
  AOI211_X1 _581_ (
    .A(_127_),
    .B(_129_),
    .C1(\trailingones[0] ),
    .C2(_339_),
    .ZN(_130_)
  );
  AOI21_X1 _582_ (
    .A(_352_),
    .B1(_180_),
    .B2(\trailingones[1] ),
    .ZN(_131_)
  );
  AOI221_X1 _583_ (
    .A(_131_),
    .B1(_064_),
    .B2(_027_),
    .C1(\trailingones[0] ),
    .C2(_334_),
    .ZN(_132_)
  );
  OAI22_X1 _584_ (
    .A1(_190_),
    .A2(_130_),
    .B1(_132_),
    .B2(\totalcoeffs[2] ),
    .ZN(_133_)
  );
  NOR2_X1 _585_ (
    .A1(_360_),
    .A2(_079_),
    .ZN(_134_)
  );
  OAI21_X1 _586_ (
    .A(_365_),
    .B1(\totalcoeffs[0] ),
    .B2(\trailingones[1] ),
    .ZN(_135_)
  );
  NAND3_X1 _587_ (
    .A1(\totalcoeffs[1] ),
    .A2(_342_),
    .A3(_135_),
    .ZN(_136_)
  );
  OAI21_X1 _588_ (
    .A(_136_),
    .B1(_074_),
    .B2(_330_),
    .ZN(_137_)
  );
  NOR2_X1 _589_ (
    .A1(\totalcoeffs[2] ),
    .A2(_055_),
    .ZN(_138_)
  );
  AOI22_X1 _590_ (
    .A1(_133_),
    .A2(_134_),
    .B1(_137_),
    .B2(_138_),
    .ZN(_140_)
  );
  OAI211_X1 _591_ (
    .A(_104_),
    .B(_140_),
    .C1(_126_),
    .C2(_124_),
    .ZN(\coeff_token[2] )
  );
  OAI211_X1 _592_ (
    .A(\totalcoeffs[3] ),
    .B(_346_),
    .C1(\trailingones[0] ),
    .C2(_128_),
    .ZN(_141_)
  );
  AND2_X1 _593_ (
    .A1(\ctable[0] ),
    .A2(\trailingones[1] ),
    .ZN(_142_)
  );
  NOR3_X1 _594_ (
    .A1(_149_),
    .A2(\ctable[1] ),
    .A3(_353_),
    .ZN(_143_)
  );
  OAI21_X1 _595_ (
    .A(\totalcoeffs[2] ),
    .B1(_034_),
    .B2(_143_),
    .ZN(_144_)
  );
  OAI211_X1 _596_ (
    .A(_141_),
    .B(_144_),
    .C1(\trailingones[0] ),
    .C2(_116_),
    .ZN(_145_)
  );
  OAI21_X1 _597_ (
    .A(_346_),
    .B1(_054_),
    .B2(_092_),
    .ZN(_146_)
  );
  NAND3_X1 _598_ (
    .A1(\totalcoeffs[4] ),
    .A2(_325_),
    .A3(_146_),
    .ZN(_147_)
  );
  NOR2_X1 _599_ (
    .A1(_190_),
    .A2(\totalcoeffs[4] ),
    .ZN(_148_)
  );
  AOI21_X1 _600_ (
    .A(\totalcoeffs[3] ),
    .B1(\ctable[1] ),
    .B2(\totalcoeffs[2] ),
    .ZN(_150_)
  );
  AOI211_X1 _601_ (
    .A(\totalcoeffs[4] ),
    .B(_150_),
    .C1(\trailingones[1] ),
    .C2(_201_),
    .ZN(_151_)
  );
  INV_X1 _602_ (
    .A(_151_),
    .ZN(_152_)
  );
  AOI21_X1 _603_ (
    .A(\totalcoeffs[1] ),
    .B1(_147_),
    .B2(_152_),
    .ZN(_153_)
  );
  AOI221_X1 _604_ (
    .A(_153_),
    .B1(_145_),
    .B2(_050_),
    .C1(_036_),
    .C2(_115_),
    .ZN(_154_)
  );
  MUX2_X1 _605_ (
    .A(_353_),
    .B(_066_),
    .S(\totalcoeffs[2] ),
    .Z(_155_)
  );
  OAI21_X1 _606_ (
    .A(_333_),
    .B1(_065_),
    .B2(\ctable[1] ),
    .ZN(_156_)
  );
  AOI21_X1 _607_ (
    .A(\totalcoeffs[3] ),
    .B1(_212_),
    .B2(_142_),
    .ZN(_157_)
  );
  OAI221_X1 _608_ (
    .A(_156_),
    .B1(_157_),
    .B2(\totalcoeffs[2] ),
    .C1(_155_),
    .C2(\trailingones[1] ),
    .ZN(_158_)
  );
  NOR2_X1 _609_ (
    .A1(_362_),
    .A2(_014_),
    .ZN(_159_)
  );
  OAI22_X1 _610_ (
    .A1(_060_),
    .A2(_116_),
    .B1(_159_),
    .B2(_086_),
    .ZN(_161_)
  );
  NOR2_X1 _611_ (
    .A1(\ctable[1] ),
    .A2(_142_),
    .ZN(_162_)
  );
  AOI211_X1 _612_ (
    .A(\ctable[1] ),
    .B(_142_),
    .C1(_026_),
    .C2(_353_),
    .ZN(_163_)
  );
  NOR3_X1 _613_ (
    .A1(_190_),
    .A2(\ctable[1] ),
    .A3(\trailingones[0] ),
    .ZN(_164_)
  );
  AOI21_X1 _614_ (
    .A(_164_),
    .B1(_115_),
    .B2(_320_),
    .ZN(_165_)
  );
  NOR2_X1 _615_ (
    .A1(\ctable[1] ),
    .A2(_287_),
    .ZN(_166_)
  );
  AOI21_X1 _616_ (
    .A(_166_),
    .B1(_115_),
    .B2(_326_),
    .ZN(_167_)
  );
  OAI22_X1 _617_ (
    .A1(\totalcoeffs[1] ),
    .A2(_165_),
    .B1(_167_),
    .B2(_316_),
    .ZN(_168_)
  );
  AOI211_X1 _618_ (
    .A(_161_),
    .B(_168_),
    .C1(_163_),
    .C2(\totalcoeffs[3] ),
    .ZN(_169_)
  );
  NOR2_X1 _619_ (
    .A1(_360_),
    .A2(_022_),
    .ZN(_170_)
  );
  AOI211_X1 _620_ (
    .A(_330_),
    .B(_360_),
    .C1(_083_),
    .C2(_117_),
    .ZN(_172_)
  );
  AOI21_X1 _621_ (
    .A(_172_),
    .B1(_170_),
    .B2(_158_),
    .ZN(_173_)
  );
  OAI221_X1 _622_ (
    .A(_173_),
    .B1(_154_),
    .B2(_019_),
    .C1(_360_),
    .C2(_169_),
    .ZN(\coeff_token[3] )
  );
  NAND2_X1 _623_ (
    .A1(_180_),
    .A2(_323_),
    .ZN(_174_)
  );
  XNOR2_X1 _624_ (
    .A(\totalcoeffs[3] ),
    .B(\totalcoeffs[4] ),
    .ZN(_175_)
  );
  OAI22_X1 _625_ (
    .A1(\totalcoeffs[4] ),
    .A2(_058_),
    .B1(_174_),
    .B2(_175_),
    .ZN(_176_)
  );
  INV_X1 _626_ (
    .A(_176_),
    .ZN(_177_)
  );
  NOR3_X1 _627_ (
    .A1(\ctable[2] ),
    .A2(_346_),
    .A3(_177_),
    .ZN(\coeff_token[4] )
  );
  NOR3_X1 _628_ (
    .A1(\totalcoeffs[3] ),
    .A2(_222_),
    .A3(_174_),
    .ZN(_178_)
  );
  AOI21_X1 _629_ (
    .A(_178_),
    .B1(_174_),
    .B2(_148_),
    .ZN(_179_)
  );
  NOR3_X1 _630_ (
    .A1(\ctable[2] ),
    .A2(_346_),
    .A3(_179_),
    .ZN(\coeff_token[5] )
  );
  OAI21_X1 _631_ (
    .A(_079_),
    .B1(_076_),
    .B2(\trailingones[0] ),
    .ZN(_181_)
  );
  AOI221_X1 _632_ (
    .A(\totalcoeffs[1] ),
    .B1(_244_),
    .B2(_069_),
    .C1(_181_),
    .C2(_335_),
    .ZN(_182_)
  );
  NOR2_X1 _633_ (
    .A1(_160_),
    .A2(_320_),
    .ZN(_183_)
  );
  OAI21_X1 _634_ (
    .A(\ctable[1] ),
    .B1(_094_),
    .B2(_183_),
    .ZN(_184_)
  );
  OAI21_X1 _635_ (
    .A(_201_),
    .B1(_160_),
    .B2(\ctable[0] ),
    .ZN(_185_)
  );
  NAND3_X1 _636_ (
    .A1(\trailingones[1] ),
    .A2(_331_),
    .A3(_185_),
    .ZN(_186_)
  );
  NAND3_X1 _637_ (
    .A1(\ctable[0] ),
    .A2(_342_),
    .A3(_028_),
    .ZN(_187_)
  );
  AND4_X1 _638_ (
    .A1(\totalcoeffs[1] ),
    .A2(_184_),
    .A3(_186_),
    .A4(_187_),
    .ZN(_188_)
  );
  AOI21_X1 _639_ (
    .A(_354_),
    .B1(_074_),
    .B2(_076_),
    .ZN(_189_)
  );
  OAI21_X1 _640_ (
    .A(_026_),
    .B1(_321_),
    .B2(\totalcoeffs[1] ),
    .ZN(_191_)
  );
  NOR2_X1 _641_ (
    .A1(_027_),
    .A2(_189_),
    .ZN(_192_)
  );
  AOI21_X1 _642_ (
    .A(_192_),
    .B1(_191_),
    .B2(\totalcoeffs[0] ),
    .ZN(_193_)
  );
  NOR2_X1 _643_ (
    .A1(_171_),
    .A2(_352_),
    .ZN(_194_)
  );
  OAI211_X1 _644_ (
    .A(\trailingones[1] ),
    .B(_160_),
    .C1(_312_),
    .C2(_194_),
    .ZN(_195_)
  );
  NAND3_X1 _645_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[0] ),
    .A3(_312_),
    .ZN(_196_)
  );
  OAI211_X1 _646_ (
    .A(_334_),
    .B(_079_),
    .C1(\totalcoeffs[0] ),
    .C2(\trailingones[0] ),
    .ZN(_197_)
  );
  AND3_X1 _647_ (
    .A1(_195_),
    .A2(_196_),
    .A3(_197_),
    .ZN(_198_)
  );
  OAI222_X1 _648_ (
    .A1(_182_),
    .A2(_188_),
    .B1(_193_),
    .B2(_333_),
    .C1(_190_),
    .C2(_198_),
    .ZN(_199_)
  );
  AOI21_X1 _649_ (
    .A(_320_),
    .B1(_025_),
    .B2(_040_),
    .ZN(_200_)
  );
  OAI21_X1 _650_ (
    .A(\trailingones[0] ),
    .B1(\trailingones[1] ),
    .B2(_139_),
    .ZN(_202_)
  );
  AOI21_X1 _651_ (
    .A(_337_),
    .B1(_202_),
    .B2(_313_),
    .ZN(_203_)
  );
  OAI22_X1 _652_ (
    .A1(_061_),
    .A2(_200_),
    .B1(_203_),
    .B2(\totalcoeffs[0] ),
    .ZN(_204_)
  );
  AOI21_X1 _653_ (
    .A(_178_),
    .B1(\ctable[1] ),
    .B2(\ctable[0] ),
    .ZN(_205_)
  );
  NAND3_X1 _654_ (
    .A1(\totalcoeffs[2] ),
    .A2(_171_),
    .A3(_363_),
    .ZN(_206_)
  );
  AOI21_X1 _655_ (
    .A(\totalcoeffs[0] ),
    .B1(_363_),
    .B2(\totalcoeffs[2] ),
    .ZN(_207_)
  );
  OAI21_X1 _656_ (
    .A(\totalcoeffs[2] ),
    .B1(\totalcoeffs[1] ),
    .B2(\ctable[0] ),
    .ZN(_208_)
  );
  AOI22_X1 _657_ (
    .A1(\ctable[0] ),
    .A2(_025_),
    .B1(_208_),
    .B2(_008_),
    .ZN(_209_)
  );
  AOI211_X1 _658_ (
    .A(_212_),
    .B(_207_),
    .C1(_209_),
    .C2(_206_),
    .ZN(_210_)
  );
  NOR3_X1 _659_ (
    .A1(_201_),
    .A2(_340_),
    .A3(_097_),
    .ZN(_211_)
  );
  NOR3_X1 _660_ (
    .A1(_149_),
    .A2(_160_),
    .A3(\totalcoeffs[0] ),
    .ZN(_213_)
  );
  OR2_X1 _661_ (
    .A1(_322_),
    .A2(_213_),
    .ZN(_214_)
  );
  AOI211_X1 _662_ (
    .A(_210_),
    .B(_211_),
    .C1(_214_),
    .C2(\ctable[0] ),
    .ZN(_215_)
  );
  NAND3_X1 _663_ (
    .A1(_139_),
    .A2(_190_),
    .A3(_222_),
    .ZN(_216_)
  );
  OAI22_X1 _664_ (
    .A1(\ctable[2] ),
    .A2(_205_),
    .B1(_215_),
    .B2(_216_),
    .ZN(_217_)
  );
  AOI221_X1 _665_ (
    .A(_217_),
    .B1(_204_),
    .B2(_056_),
    .C1(_359_),
    .C2(_199_),
    .ZN(\ctoken_len[0] )
  );
  NAND2_X1 _666_ (
    .A1(_324_),
    .A2(_326_),
    .ZN(_218_)
  );
  OAI21_X1 _667_ (
    .A(_287_),
    .B1(_097_),
    .B2(_218_),
    .ZN(_219_)
  );
  NAND2_X1 _668_ (
    .A1(\ctable[0] ),
    .A2(_219_),
    .ZN(_220_)
  );
  NOR3_X1 _669_ (
    .A1(_149_),
    .A2(_287_),
    .A3(_353_),
    .ZN(_221_)
  );
  NOR3_X1 _670_ (
    .A1(_160_),
    .A2(_321_),
    .A3(_003_),
    .ZN(_223_)
  );
  NOR3_X1 _671_ (
    .A1(\totalcoeffs[1] ),
    .A2(_221_),
    .A3(_223_),
    .ZN(_224_)
  );
  NOR3_X1 _672_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[0] ),
    .A3(_353_),
    .ZN(_225_)
  );
  AOI221_X1 _673_ (
    .A(_225_),
    .B1(_040_),
    .B2(_340_),
    .C1(_244_),
    .C2(_012_),
    .ZN(_226_)
  );
  NOR2_X1 _674_ (
    .A1(_180_),
    .A2(_221_),
    .ZN(_227_)
  );
  NAND2_X1 _675_ (
    .A1(\ctable[0] ),
    .A2(\totalcoeffs[3] ),
    .ZN(_228_)
  );
  NAND2_X1 _676_ (
    .A1(_339_),
    .A2(_228_),
    .ZN(_229_)
  );
  NOR3_X1 _677_ (
    .A1(_128_),
    .A2(_086_),
    .A3(_093_),
    .ZN(_230_)
  );
  AOI21_X1 _678_ (
    .A(_230_),
    .B1(_229_),
    .B2(_331_),
    .ZN(_231_)
  );
  OAI211_X1 _679_ (
    .A(_227_),
    .B(_231_),
    .C1(\totalcoeffs[3] ),
    .C2(_226_),
    .ZN(_232_)
  );
  NOR2_X1 _680_ (
    .A1(\ctable[1] ),
    .A2(_360_),
    .ZN(_234_)
  );
  AOI211_X1 _681_ (
    .A(\ctable[1] ),
    .B(_360_),
    .C1(_220_),
    .C2(_224_),
    .ZN(_235_)
  );
  OAI221_X1 _682_ (
    .A(_180_),
    .B1(_321_),
    .B2(_324_),
    .C1(_330_),
    .C2(_352_),
    .ZN(_236_)
  );
  NAND3_X1 _683_ (
    .A1(_171_),
    .A2(\totalcoeffs[3] ),
    .A3(\ctable[1] ),
    .ZN(_237_)
  );
  OAI211_X1 _684_ (
    .A(\totalcoeffs[2] ),
    .B(_321_),
    .C1(_064_),
    .C2(\ctable[1] ),
    .ZN(_238_)
  );
  OAI21_X1 _685_ (
    .A(_238_),
    .B1(_237_),
    .B2(_097_),
    .ZN(_239_)
  );
  NOR4_X1 _686_ (
    .A1(\ctable[1] ),
    .A2(_329_),
    .A3(_086_),
    .A4(_093_),
    .ZN(_240_)
  );
  NOR4_X1 _687_ (
    .A1(_190_),
    .A2(_201_),
    .A3(\trailingones[0] ),
    .A4(_336_),
    .ZN(_241_)
  );
  NOR4_X1 _688_ (
    .A1(_236_),
    .A2(_239_),
    .A3(_240_),
    .A4(_241_),
    .ZN(_242_)
  );
  NAND2_X1 _689_ (
    .A1(_092_),
    .A2(_166_),
    .ZN(_243_)
  );
  OAI21_X1 _690_ (
    .A(_032_),
    .B1(_212_),
    .B2(\totalcoeffs[3] ),
    .ZN(_245_)
  );
  NAND2_X1 _691_ (
    .A1(_370_),
    .A2(_245_),
    .ZN(_246_)
  );
  NOR4_X1 _692_ (
    .A1(\totalcoeffs[0] ),
    .A2(_190_),
    .A3(\ctable[1] ),
    .A4(_212_),
    .ZN(_247_)
  );
  OAI211_X1 _693_ (
    .A(\trailingones[1] ),
    .B(_160_),
    .C1(_105_),
    .C2(_247_),
    .ZN(_248_)
  );
  NOR3_X1 _694_ (
    .A1(_160_),
    .A2(\totalcoeffs[3] ),
    .A3(_092_),
    .ZN(_249_)
  );
  OAI33_X1 _695_ (
    .A1(\totalcoeffs[3] ),
    .A2(\trailingones[0] ),
    .A3(_009_),
    .B1(_041_),
    .B2(\ctable[1] ),
    .B3(_160_),
    .ZN(_250_)
  );
  OAI21_X1 _696_ (
    .A(\totalcoeffs[1] ),
    .B1(_336_),
    .B2(_352_),
    .ZN(_251_)
  );
  NOR4_X1 _697_ (
    .A1(_241_),
    .A2(_249_),
    .A3(_250_),
    .A4(_251_),
    .ZN(_252_)
  );
  AND4_X1 _698_ (
    .A1(_243_),
    .A2(_246_),
    .A3(_248_),
    .A4(_252_),
    .ZN(_253_)
  );
  NOR4_X1 _699_ (
    .A1(\ctable[0] ),
    .A2(_360_),
    .A3(_242_),
    .A4(_253_),
    .ZN(_254_)
  );
  NAND2_X1 _700_ (
    .A1(_005_),
    .A2(_097_),
    .ZN(_256_)
  );
  NOR4_X1 _701_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[2] ),
    .A3(_171_),
    .A4(_365_),
    .ZN(_257_)
  );
  AOI21_X1 _702_ (
    .A(_257_),
    .B1(_097_),
    .B2(_005_),
    .ZN(_258_)
  );
  NAND3_X1 _703_ (
    .A1(_139_),
    .A2(\totalcoeffs[4] ),
    .A3(_021_),
    .ZN(_259_)
  );
  NOR2_X1 _704_ (
    .A1(_174_),
    .A2(_259_),
    .ZN(_260_)
  );
  OAI33_X1 _705_ (
    .A1(\totalcoeffs[1] ),
    .A2(_055_),
    .A3(_258_),
    .B1(_259_),
    .B2(_174_),
    .B3(\ctable[1] ),
    .ZN(_261_)
  );
  AOI211_X1 _706_ (
    .A(_254_),
    .B(_261_),
    .C1(_232_),
    .C2(_235_),
    .ZN(\ctoken_len[1] )
  );
  NOR3_X1 _707_ (
    .A1(_128_),
    .A2(\totalcoeffs[2] ),
    .A3(_276_),
    .ZN(_262_)
  );
  OR2_X1 _708_ (
    .A1(_108_),
    .A2(_262_),
    .ZN(_263_)
  );
  OAI211_X1 _709_ (
    .A(_276_),
    .B(_026_),
    .C1(\ctable[0] ),
    .C2(\totalcoeffs[1] ),
    .ZN(_264_)
  );
  AOI21_X1 _710_ (
    .A(_021_),
    .B1(_180_),
    .B2(\ctable[0] ),
    .ZN(_266_)
  );
  NOR4_X1 _711_ (
    .A1(\totalcoeffs[2] ),
    .A2(_265_),
    .A3(_314_),
    .A4(_266_),
    .ZN(_267_)
  );
  AOI221_X1 _712_ (
    .A(_267_),
    .B1(_264_),
    .B2(_317_),
    .C1(_171_),
    .C2(_263_),
    .ZN(_268_)
  );
  AOI21_X1 _713_ (
    .A(_118_),
    .B1(_228_),
    .B2(_110_),
    .ZN(_269_)
  );
  OAI211_X1 _714_ (
    .A(_160_),
    .B(\trailingones[0] ),
    .C1(\totalcoeffs[0] ),
    .C2(_128_),
    .ZN(_270_)
  );
  NOR3_X1 _715_ (
    .A1(\totalcoeffs[1] ),
    .A2(_190_),
    .A3(_270_),
    .ZN(_271_)
  );
  AOI211_X1 _716_ (
    .A(_149_),
    .B(_271_),
    .C1(_269_),
    .C2(\totalcoeffs[1] ),
    .ZN(_272_)
  );
  OAI33_X1 _717_ (
    .A1(\totalcoeffs[1] ),
    .A2(\totalcoeffs[3] ),
    .A3(_079_),
    .B1(_266_),
    .B2(_338_),
    .B3(\totalcoeffs[2] ),
    .ZN(_273_)
  );
  AOI21_X1 _718_ (
    .A(\trailingones[1] ),
    .B1(_354_),
    .B2(_228_),
    .ZN(_274_)
  );
  AOI21_X1 _719_ (
    .A(_274_),
    .B1(_070_),
    .B2(_362_),
    .ZN(_275_)
  );
  AOI21_X1 _720_ (
    .A(_275_),
    .B1(_273_),
    .B2(\trailingones[0] ),
    .ZN(_277_)
  );
  OAI22_X1 _721_ (
    .A1(\trailingones[0] ),
    .A2(_268_),
    .B1(_272_),
    .B2(_277_),
    .ZN(_278_)
  );
  OAI211_X1 _722_ (
    .A(\totalcoeffs[2] ),
    .B(\totalcoeffs[0] ),
    .C1(\totalcoeffs[1] ),
    .C2(_320_),
    .ZN(_279_)
  );
  OAI21_X1 _723_ (
    .A(\totalcoeffs[2] ),
    .B1(\ctable[1] ),
    .B2(_312_),
    .ZN(_280_)
  );
  OAI211_X1 _724_ (
    .A(\ctable[1] ),
    .B(_316_),
    .C1(_334_),
    .C2(_070_),
    .ZN(_281_)
  );
  NAND3_X1 _725_ (
    .A1(_279_),
    .A2(_280_),
    .A3(_281_),
    .ZN(_282_)
  );
  NOR2_X1 _726_ (
    .A1(_333_),
    .A2(_360_),
    .ZN(_283_)
  );
  OAI21_X1 _727_ (
    .A(_335_),
    .B1(_040_),
    .B2(_331_),
    .ZN(_284_)
  );
  AOI211_X1 _728_ (
    .A(\totalcoeffs[1] ),
    .B(_055_),
    .C1(_256_),
    .C2(_284_),
    .ZN(_285_)
  );
  NOR4_X1 _729_ (
    .A1(\trailingones[0] ),
    .A2(_324_),
    .A3(_026_),
    .A4(_055_),
    .ZN(_286_)
  );
  OR3_X1 _730_ (
    .A1(_260_),
    .A2(_285_),
    .A3(_286_),
    .ZN(_288_)
  );
  AOI221_X1 _731_ (
    .A(_288_),
    .B1(_283_),
    .B2(_282_),
    .C1(_234_),
    .C2(_278_),
    .ZN(\ctoken_len[2] )
  );
  NOR2_X1 _732_ (
    .A1(\totalcoeffs[3] ),
    .A2(_362_),
    .ZN(_289_)
  );
  AOI21_X1 _733_ (
    .A(\totalcoeffs[2] ),
    .B1(\totalcoeffs[3] ),
    .B2(_032_),
    .ZN(_290_)
  );
  OAI21_X1 _734_ (
    .A(_290_),
    .B1(_289_),
    .B2(_069_),
    .ZN(_291_)
  );
  OR3_X1 _735_ (
    .A1(\totalcoeffs[3] ),
    .A2(_014_),
    .A3(_162_),
    .ZN(_292_)
  );
  OAI211_X1 _736_ (
    .A(_291_),
    .B(_292_),
    .C1(\ctable[0] ),
    .C2(_243_),
    .ZN(_293_)
  );
  OAI211_X1 _737_ (
    .A(_313_),
    .B(_289_),
    .C1(_142_),
    .C2(\trailingones[0] ),
    .ZN(_294_)
  );
  OAI21_X1 _738_ (
    .A(\totalcoeffs[4] ),
    .B1(_326_),
    .B2(\totalcoeffs[1] ),
    .ZN(_295_)
  );
  OAI21_X1 _739_ (
    .A(\ctable[1] ),
    .B1(_317_),
    .B2(\ctable[0] ),
    .ZN(_296_)
  );
  NAND2_X1 _740_ (
    .A1(_171_),
    .A2(_317_),
    .ZN(_298_)
  );
  AOI22_X1 _741_ (
    .A1(\totalcoeffs[0] ),
    .A2(_018_),
    .B1(_298_),
    .B2(\ctable[2] ),
    .ZN(_299_)
  );
  NAND4_X1 _742_ (
    .A1(_294_),
    .A2(_295_),
    .A3(_296_),
    .A4(_299_),
    .ZN(_300_)
  );
  NOR3_X1 _743_ (
    .A1(\ctable[1] ),
    .A2(_287_),
    .A3(_079_),
    .ZN(_301_)
  );
  OAI22_X1 _744_ (
    .A1(\totalcoeffs[1] ),
    .A2(_320_),
    .B1(_301_),
    .B2(\ctable[2] ),
    .ZN(_302_)
  );
  OAI211_X1 _745_ (
    .A(\totalcoeffs[3] ),
    .B(_032_),
    .C1(_070_),
    .C2(_162_),
    .ZN(_303_)
  );
  NAND3_X1 _746_ (
    .A1(_190_),
    .A2(\totalcoeffs[4] ),
    .A3(_054_),
    .ZN(_304_)
  );
  NAND4_X1 _747_ (
    .A1(_160_),
    .A2(_180_),
    .A3(_303_),
    .A4(_304_),
    .ZN(_305_)
  );
  NAND2_X1 _748_ (
    .A1(_302_),
    .A2(_305_),
    .ZN(_306_)
  );
  AOI211_X1 _749_ (
    .A(_300_),
    .B(_306_),
    .C1(\totalcoeffs[1] ),
    .C2(_293_),
    .ZN(\ctoken_len[3] )
  );
  AOI21_X1 _750_ (
    .A(\totalcoeffs[1] ),
    .B1(_320_),
    .B2(\totalcoeffs[0] ),
    .ZN(_308_)
  );
  OAI211_X1 _751_ (
    .A(\totalcoeffs[3] ),
    .B(_036_),
    .C1(_092_),
    .C2(\totalcoeffs[0] ),
    .ZN(_309_)
  );
  NOR2_X1 _752_ (
    .A1(_308_),
    .A2(_309_),
    .ZN(_310_)
  );
  NOR2_X1 _753_ (
    .A1(_178_),
    .A2(_310_),
    .ZN(_311_)
  );
  NOR3_X1 _754_ (
    .A1(\ctable[2] ),
    .A2(_054_),
    .A3(_311_),
    .ZN(\ctoken_len[4] )
  );
endmodule
