/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module top(\totalcoeffs[0] , \totalcoeffs[1] , \totalcoeffs[2] , \totalcoeffs[3] , \totalcoeffs[4] , \ctable[0] , \ctable[1] , \ctable[2] , \trailingones[0] , \trailingones[1] , \coeff_token[0] , \coeff_token[1] , \coeff_token[2] , \coeff_token[3] , \coeff_token[4] , \coeff_token[5] , \ctoken_len[0] , \ctoken_len[1] , \ctoken_len[2] , \ctoken_len[3] , \ctoken_len[4] );
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  output \coeff_token[0] ;
  output \coeff_token[1] ;
  output \coeff_token[2] ;
  output \coeff_token[3] ;
  output \coeff_token[4] ;
  output \coeff_token[5] ;
  input \ctable[0] ;
  input \ctable[1] ;
  input \ctable[2] ;
  output \ctoken_len[0] ;
  output \ctoken_len[1] ;
  output \ctoken_len[2] ;
  output \ctoken_len[3] ;
  output \ctoken_len[4] ;
  input \totalcoeffs[0] ;
  input \totalcoeffs[1] ;
  input \totalcoeffs[2] ;
  input \totalcoeffs[3] ;
  input \totalcoeffs[4] ;
  input \trailingones[0] ;
  input \trailingones[1] ;
  INV_X1 _351_ (
    .A(\ctable[0] ),
    .ZN(_127_)
  );
  INV_X1 _352_ (
    .A(\ctable[2] ),
    .ZN(_138_)
  );
  INV_X1 _353_ (
    .A(\trailingones[1] ),
    .ZN(_149_)
  );
  INV_X1 _354_ (
    .A(\totalcoeffs[2] ),
    .ZN(_159_)
  );
  INV_X1 _355_ (
    .A(\totalcoeffs[0] ),
    .ZN(_168_)
  );
  INV_X1 _356_ (
    .A(\totalcoeffs[1] ),
    .ZN(_179_)
  );
  INV_X1 _357_ (
    .A(\totalcoeffs[3] ),
    .ZN(_190_)
  );
  INV_X1 _358_ (
    .A(\ctable[1] ),
    .ZN(_200_)
  );
  INV_X1 _359_ (
    .A(\trailingones[0] ),
    .ZN(_211_)
  );
  INV_X1 _360_ (
    .A(\totalcoeffs[4] ),
    .ZN(_222_)
  );
  NOR2_X1 _361_ (
    .A1(\trailingones[1] ),
    .A2(\ctable[1] ),
    .ZN(_233_)
  );
  AOI21_X1 _362_ (
    .A(_233_),
    .B1(\totalcoeffs[4] ),
    .B2(\trailingones[0] ),
    .ZN(_243_)
  );
  NAND2_X1 _363_ (
    .A1(\ctable[0] ),
    .A2(\ctable[1] ),
    .ZN(_254_)
  );
  NOR2_X1 _364_ (
    .A1(_127_),
    .A2(\trailingones[0] ),
    .ZN(_265_)
  );
  NAND2_X1 _365_ (
    .A1(\ctable[0] ),
    .A2(_211_),
    .ZN(_275_)
  );
  AOI21_X1 _366_ (
    .A(_243_),
    .B1(_254_),
    .B2(_275_),
    .ZN(_286_)
  );
  NAND2_X1 _367_ (
    .A1(_149_),
    .A2(\ctable[1] ),
    .ZN(_289_)
  );
  NAND2_X1 _368_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[4] ),
    .ZN(_290_)
  );
  AOI221_X1 _369_ (
    .A(\trailingones[0] ),
    .B1(_289_),
    .B2(_290_),
    .C1(\ctable[1] ),
    .C2(\ctable[0] ),
    .ZN(_291_)
  );
  NOR2_X1 _370_ (
    .A1(\totalcoeffs[2] ),
    .A2(\totalcoeffs[3] ),
    .ZN(_292_)
  );
  NAND2_X1 _371_ (
    .A1(_159_),
    .A2(_190_),
    .ZN(_293_)
  );
  NOR2_X1 _372_ (
    .A1(\ctable[2] ),
    .A2(_293_),
    .ZN(_294_)
  );
  NOR2_X1 _373_ (
    .A1(\totalcoeffs[0] ),
    .A2(\totalcoeffs[1] ),
    .ZN(_295_)
  );
  OAI211_X1 _374_ (
    .A(_294_),
    .B(_295_),
    .C1(_286_),
    .C2(_291_),
    .ZN(_296_)
  );
  NAND3_X1 _375_ (
    .A1(_127_),
    .A2(\ctable[2] ),
    .A3(\trailingones[0] ),
    .ZN(_297_)
  );
  NOR2_X1 _376_ (
    .A1(_159_),
    .A2(\totalcoeffs[1] ),
    .ZN(_298_)
  );
  NAND2_X1 _377_ (
    .A1(_149_),
    .A2(\totalcoeffs[2] ),
    .ZN(_299_)
  );
  NOR2_X1 _378_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[1] ),
    .ZN(_300_)
  );
  OR2_X1 _379_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[1] ),
    .ZN(_301_)
  );
  NOR2_X1 _380_ (
    .A1(_159_),
    .A2(\totalcoeffs[0] ),
    .ZN(_302_)
  );
  NOR2_X1 _381_ (
    .A1(\totalcoeffs[2] ),
    .A2(_168_),
    .ZN(_303_)
  );
  NAND2_X1 _382_ (
    .A1(_159_),
    .A2(\totalcoeffs[0] ),
    .ZN(_304_)
  );
  AOI22_X1 _383_ (
    .A1(_300_),
    .A2(_302_),
    .B1(_303_),
    .B2(\totalcoeffs[1] ),
    .ZN(_305_)
  );
  OR2_X1 _384_ (
    .A1(\ctable[0] ),
    .A2(\trailingones[1] ),
    .ZN(_306_)
  );
  AOI21_X1 _385_ (
    .A(_306_),
    .B1(\totalcoeffs[1] ),
    .B2(_138_),
    .ZN(_307_)
  );
  NAND2_X1 _386_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[1] ),
    .ZN(_308_)
  );
  INV_X1 _387_ (
    .A(_308_),
    .ZN(_309_)
  );
  NOR2_X1 _388_ (
    .A1(\ctable[2] ),
    .A2(_308_),
    .ZN(_310_)
  );
  OAI21_X1 _389_ (
    .A(_303_),
    .B1(_307_),
    .B2(_310_),
    .ZN(_311_)
  );
  OAI21_X1 _390_ (
    .A(_311_),
    .B1(_305_),
    .B2(_297_),
    .ZN(_312_)
  );
  NAND2_X1 _391_ (
    .A1(_190_),
    .A2(_312_),
    .ZN(_313_)
  );
  NOR2_X1 _392_ (
    .A1(_149_),
    .A2(_159_),
    .ZN(_314_)
  );
  NAND2_X1 _393_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[2] ),
    .ZN(_315_)
  );
  AOI221_X1 _394_ (
    .A(\totalcoeffs[1] ),
    .B1(_190_),
    .B2(_315_),
    .C1(_168_),
    .C2(_149_),
    .ZN(_316_)
  );
  NOR2_X1 _395_ (
    .A1(_179_),
    .A2(\totalcoeffs[3] ),
    .ZN(_317_)
  );
  NAND2_X1 _396_ (
    .A1(\totalcoeffs[2] ),
    .A2(\totalcoeffs[1] ),
    .ZN(_318_)
  );
  OAI21_X1 _397_ (
    .A(_168_),
    .B1(\totalcoeffs[2] ),
    .B2(\ctable[0] ),
    .ZN(_319_)
  );
  AOI21_X1 _398_ (
    .A(\trailingones[1] ),
    .B1(_318_),
    .B2(_319_),
    .ZN(_320_)
  );
  NOR3_X1 _399_ (
    .A1(_316_),
    .A2(_317_),
    .A3(_320_),
    .ZN(_321_)
  );
  NOR2_X1 _400_ (
    .A1(_168_),
    .A2(_179_),
    .ZN(_322_)
  );
  NOR2_X1 _401_ (
    .A1(\ctable[0] ),
    .A2(\totalcoeffs[3] ),
    .ZN(_323_)
  );
  NAND2_X1 _402_ (
    .A1(_127_),
    .A2(_190_),
    .ZN(_324_)
  );
  OAI22_X1 _403_ (
    .A1(\ctable[2] ),
    .A2(_295_),
    .B1(_322_),
    .B2(_324_),
    .ZN(_325_)
  );
  NAND2_X1 _404_ (
    .A1(_301_),
    .A2(_308_),
    .ZN(_326_)
  );
  NAND2_X1 _405_ (
    .A1(\trailingones[1] ),
    .A2(_168_),
    .ZN(_327_)
  );
  NAND2_X1 _406_ (
    .A1(_149_),
    .A2(\totalcoeffs[1] ),
    .ZN(_328_)
  );
  NAND2_X1 _407_ (
    .A1(\totalcoeffs[1] ),
    .A2(_327_),
    .ZN(_329_)
  );
  NOR2_X1 _408_ (
    .A1(_149_),
    .A2(\totalcoeffs[1] ),
    .ZN(_330_)
  );
  NOR2_X1 _409_ (
    .A1(\trailingones[1] ),
    .A2(_168_),
    .ZN(_331_)
  );
  NOR2_X1 _410_ (
    .A1(\totalcoeffs[2] ),
    .A2(\trailingones[0] ),
    .ZN(_332_)
  );
  OR2_X1 _411_ (
    .A1(\totalcoeffs[2] ),
    .A2(\trailingones[0] ),
    .ZN(_333_)
  );
  NAND3_X1 _412_ (
    .A1(_325_),
    .A2(_326_),
    .A3(_332_),
    .ZN(_334_)
  );
  AOI21_X1 _413_ (
    .A(\ctable[1] ),
    .B1(_313_),
    .B2(_334_),
    .ZN(_335_)
  );
  NOR2_X1 _414_ (
    .A1(\ctable[1] ),
    .A2(\trailingones[0] ),
    .ZN(_336_)
  );
  NOR4_X1 _415_ (
    .A1(\ctable[2] ),
    .A2(\ctable[1] ),
    .A3(\trailingones[0] ),
    .A4(_321_),
    .ZN(_337_)
  );
  NOR2_X1 _416_ (
    .A1(_179_),
    .A2(\trailingones[0] ),
    .ZN(_338_)
  );
  NOR2_X1 _417_ (
    .A1(\totalcoeffs[0] ),
    .A2(\trailingones[0] ),
    .ZN(_339_)
  );
  OR2_X1 _418_ (
    .A1(\totalcoeffs[0] ),
    .A2(\trailingones[0] ),
    .ZN(_340_)
  );
  AOI221_X1 _419_ (
    .A(_338_),
    .B1(_339_),
    .B2(_301_),
    .C1(_331_),
    .C2(_298_),
    .ZN(_341_)
  );
  XOR2_X1 _420_ (
    .A(\trailingones[1] ),
    .B(\totalcoeffs[0] ),
    .Z(_342_)
  );
  NAND2_X1 _421_ (
    .A1(\totalcoeffs[2] ),
    .A2(\trailingones[0] ),
    .ZN(_343_)
  );
  NAND2_X1 _422_ (
    .A1(\ctable[0] ),
    .A2(\trailingones[0] ),
    .ZN(_344_)
  );
  OR3_X1 _423_ (
    .A1(\totalcoeffs[2] ),
    .A2(\totalcoeffs[0] ),
    .A3(\totalcoeffs[1] ),
    .ZN(_345_)
  );
  NAND2_X1 _424_ (
    .A1(\trailingones[1] ),
    .A2(\ctable[1] ),
    .ZN(_346_)
  );
  OAI21_X1 _425_ (
    .A(_254_),
    .B1(_345_),
    .B2(_346_),
    .ZN(_347_)
  );
  NOR3_X1 _426_ (
    .A1(_127_),
    .A2(_318_),
    .A3(_342_),
    .ZN(_348_)
  );
  NOR2_X1 _427_ (
    .A1(_347_),
    .A2(_348_),
    .ZN(_349_)
  );
  OAI22_X1 _428_ (
    .A1(\ctable[0] ),
    .A2(_341_),
    .B1(_349_),
    .B2(_211_),
    .ZN(_350_)
  );
  NOR2_X1 _429_ (
    .A1(_159_),
    .A2(\totalcoeffs[3] ),
    .ZN(_000_)
  );
  NAND2_X1 _430_ (
    .A1(\totalcoeffs[2] ),
    .A2(_190_),
    .ZN(_001_)
  );
  AOI21_X1 _431_ (
    .A(_338_),
    .B1(_000_),
    .B2(_330_),
    .ZN(_002_)
  );
  NAND2_X1 _432_ (
    .A1(\totalcoeffs[3] ),
    .A2(_200_),
    .ZN(_003_)
  );
  NAND2_X1 _433_ (
    .A1(\totalcoeffs[2] ),
    .A2(\totalcoeffs[3] ),
    .ZN(_004_)
  );
  AOI21_X1 _434_ (
    .A(_301_),
    .B1(_200_),
    .B2(\totalcoeffs[3] ),
    .ZN(_005_)
  );
  AOI21_X1 _435_ (
    .A(_314_),
    .B1(_004_),
    .B2(_005_),
    .ZN(_006_)
  );
  OAI22_X1 _436_ (
    .A1(\totalcoeffs[0] ),
    .A2(_002_),
    .B1(_006_),
    .B2(\trailingones[0] ),
    .ZN(_007_)
  );
  NOR2_X1 _437_ (
    .A1(\trailingones[1] ),
    .A2(\trailingones[0] ),
    .ZN(_008_)
  );
  NAND2_X1 _438_ (
    .A1(\totalcoeffs[1] ),
    .A2(\trailingones[0] ),
    .ZN(_009_)
  );
  OAI33_X1 _439_ (
    .A1(\totalcoeffs[0] ),
    .A2(\trailingones[0] ),
    .A3(_301_),
    .B1(_342_),
    .B2(_009_),
    .B3(_127_),
    .ZN(_010_)
  );
  NAND2_X1 _440_ (
    .A1(_292_),
    .A2(_010_),
    .ZN(_011_)
  );
  NAND2_X1 _441_ (
    .A1(_159_),
    .A2(\totalcoeffs[1] ),
    .ZN(_012_)
  );
  NOR2_X1 _442_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[2] ),
    .ZN(_013_)
  );
  OR2_X1 _443_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[2] ),
    .ZN(_014_)
  );
  OAI21_X1 _444_ (
    .A(_315_),
    .B1(_014_),
    .B2(_179_),
    .ZN(_015_)
  );
  NAND3_X1 _445_ (
    .A1(_168_),
    .A2(_190_),
    .A3(_015_),
    .ZN(_016_)
  );
  OAI21_X1 _446_ (
    .A(\ctable[0] ),
    .B1(\totalcoeffs[2] ),
    .B2(_331_),
    .ZN(_017_)
  );
  NAND2_X1 _447_ (
    .A1(\ctable[1] ),
    .A2(\trailingones[0] ),
    .ZN(_018_)
  );
  AOI21_X1 _448_ (
    .A(_018_),
    .B1(_017_),
    .B2(_016_),
    .ZN(_019_)
  );
  AOI221_X1 _449_ (
    .A(_019_),
    .B1(_350_),
    .B2(\totalcoeffs[3] ),
    .C1(_127_),
    .C2(_007_),
    .ZN(_020_)
  );
  AOI21_X1 _450_ (
    .A(\ctable[2] ),
    .B1(_011_),
    .B2(_020_),
    .ZN(_021_)
  );
  NOR3_X1 _451_ (
    .A1(_335_),
    .A2(_337_),
    .A3(_021_),
    .ZN(_022_)
  );
  OAI21_X1 _452_ (
    .A(_296_),
    .B1(_022_),
    .B2(\totalcoeffs[4] ),
    .ZN(\coeff_token[0] )
  );
  AOI21_X1 _453_ (
    .A(_265_),
    .B1(\totalcoeffs[4] ),
    .B2(\trailingones[0] ),
    .ZN(_023_)
  );
  OAI21_X1 _454_ (
    .A(_290_),
    .B1(_023_),
    .B2(\ctable[1] ),
    .ZN(_024_)
  );
  AOI211_X1 _455_ (
    .A(\totalcoeffs[2] ),
    .B(\totalcoeffs[0] ),
    .C1(_200_),
    .C2(\trailingones[1] ),
    .ZN(_025_)
  );
  NAND2_X1 _456_ (
    .A1(\totalcoeffs[0] ),
    .A2(\trailingones[0] ),
    .ZN(_026_)
  );
  OAI22_X1 _457_ (
    .A1(_340_),
    .A2(_014_),
    .B1(_026_),
    .B2(_315_),
    .ZN(_027_)
  );
  OAI21_X1 _458_ (
    .A(_346_),
    .B1(_211_),
    .B2(\ctable[0] ),
    .ZN(_028_)
  );
  AOI221_X1 _459_ (
    .A(_159_),
    .B1(_306_),
    .B2(_018_),
    .C1(\trailingones[0] ),
    .C2(_149_),
    .ZN(_029_)
  );
  AOI221_X1 _460_ (
    .A(_029_),
    .B1(_028_),
    .B2(_302_),
    .C1(\ctable[0] ),
    .C2(_027_),
    .ZN(_030_)
  );
  NOR2_X1 _461_ (
    .A1(\totalcoeffs[4] ),
    .A2(_030_),
    .ZN(_031_)
  );
  AOI21_X1 _462_ (
    .A(_031_),
    .B1(_025_),
    .B2(_024_),
    .ZN(_032_)
  );
  NOR2_X1 _463_ (
    .A1(\totalcoeffs[2] ),
    .A2(\ctable[1] ),
    .ZN(_033_)
  );
  NOR3_X1 _464_ (
    .A1(\ctable[0] ),
    .A2(_211_),
    .A3(_033_),
    .ZN(_034_)
  );
  AOI21_X1 _465_ (
    .A(_336_),
    .B1(_034_),
    .B2(_304_),
    .ZN(_035_)
  );
  NOR3_X1 _466_ (
    .A1(\trailingones[1] ),
    .A2(\ctable[1] ),
    .A3(_343_),
    .ZN(_036_)
  );
  NOR2_X1 _467_ (
    .A1(_127_),
    .A2(_149_),
    .ZN(_037_)
  );
  NOR2_X1 _468_ (
    .A1(_149_),
    .A2(\trailingones[0] ),
    .ZN(_038_)
  );
  AND2_X1 _469_ (
    .A1(\totalcoeffs[0] ),
    .A2(_018_),
    .ZN(_039_)
  );
  AOI22_X1 _470_ (
    .A1(_339_),
    .A2(_037_),
    .B1(_039_),
    .B2(_028_),
    .ZN(_040_)
  );
  OAI22_X1 _471_ (
    .A1(\trailingones[1] ),
    .A2(_035_),
    .B1(_040_),
    .B2(\totalcoeffs[2] ),
    .ZN(_041_)
  );
  AOI21_X1 _472_ (
    .A(_036_),
    .B1(_041_),
    .B2(\totalcoeffs[1] ),
    .ZN(_042_)
  );
  OAI22_X1 _473_ (
    .A1(\totalcoeffs[1] ),
    .A2(_032_),
    .B1(_042_),
    .B2(\totalcoeffs[4] ),
    .ZN(_043_)
  );
  NOR2_X1 _474_ (
    .A1(\totalcoeffs[2] ),
    .A2(_211_),
    .ZN(_044_)
  );
  NOR2_X1 _475_ (
    .A1(\totalcoeffs[2] ),
    .A2(_026_),
    .ZN(_045_)
  );
  NAND2_X1 _476_ (
    .A1(\totalcoeffs[0] ),
    .A2(_044_),
    .ZN(_046_)
  );
  NAND2_X1 _477_ (
    .A1(_127_),
    .A2(\totalcoeffs[0] ),
    .ZN(_047_)
  );
  XOR2_X1 _478_ (
    .A(\ctable[0] ),
    .B(\totalcoeffs[0] ),
    .Z(_048_)
  );
  OAI21_X1 _479_ (
    .A(\totalcoeffs[1] ),
    .B1(_045_),
    .B2(_048_),
    .ZN(_049_)
  );
  NOR2_X1 _480_ (
    .A1(\totalcoeffs[3] ),
    .A2(\trailingones[0] ),
    .ZN(_050_)
  );
  NOR2_X1 _481_ (
    .A1(_190_),
    .A2(\trailingones[0] ),
    .ZN(_051_)
  );
  AOI21_X1 _482_ (
    .A(_050_),
    .B1(\trailingones[0] ),
    .B2(_127_),
    .ZN(_052_)
  );
  AOI21_X1 _483_ (
    .A(\totalcoeffs[2] ),
    .B1(\totalcoeffs[3] ),
    .B2(\trailingones[0] ),
    .ZN(_053_)
  );
  NOR2_X1 _484_ (
    .A1(\totalcoeffs[1] ),
    .A2(\ctable[1] ),
    .ZN(_054_)
  );
  NOR2_X1 _485_ (
    .A1(\totalcoeffs[0] ),
    .A2(_211_),
    .ZN(_055_)
  );
  NAND2_X1 _486_ (
    .A1(_168_),
    .A2(\trailingones[0] ),
    .ZN(_056_)
  );
  NAND2_X1 _487_ (
    .A1(_159_),
    .A2(_056_),
    .ZN(_057_)
  );
  NOR2_X1 _488_ (
    .A1(\totalcoeffs[1] ),
    .A2(\trailingones[0] ),
    .ZN(_058_)
  );
  AOI21_X1 _489_ (
    .A(_159_),
    .B1(_179_),
    .B2(\ctable[1] ),
    .ZN(_059_)
  );
  OAI33_X1 _490_ (
    .A1(_322_),
    .A2(_054_),
    .A3(_057_),
    .B1(_058_),
    .B2(_059_),
    .B3(_190_),
    .ZN(_060_)
  );
  NAND2_X1 _491_ (
    .A1(\ctable[0] ),
    .A2(_159_),
    .ZN(_061_)
  );
  NAND3_X1 _492_ (
    .A1(\ctable[0] ),
    .A2(_332_),
    .A3(_054_),
    .ZN(_062_)
  );
  NOR2_X1 _493_ (
    .A1(\totalcoeffs[2] ),
    .A2(_190_),
    .ZN(_063_)
  );
  AOI22_X1 _494_ (
    .A1(\ctable[0] ),
    .A2(\totalcoeffs[1] ),
    .B1(_058_),
    .B2(_063_),
    .ZN(_064_)
  );
  OAI21_X1 _495_ (
    .A(\totalcoeffs[2] ),
    .B1(\totalcoeffs[1] ),
    .B2(\ctable[0] ),
    .ZN(_065_)
  );
  NAND2_X1 _496_ (
    .A1(\ctable[0] ),
    .A2(\totalcoeffs[3] ),
    .ZN(_066_)
  );
  NOR2_X1 _497_ (
    .A1(_190_),
    .A2(_318_),
    .ZN(_067_)
  );
  OAI221_X1 _498_ (
    .A(_066_),
    .B1(_065_),
    .B2(_323_),
    .C1(_168_),
    .C2(_064_),
    .ZN(_068_)
  );
  AOI22_X1 _499_ (
    .A1(\ctable[0] ),
    .A2(_332_),
    .B1(_052_),
    .B2(\totalcoeffs[0] ),
    .ZN(_069_)
  );
  OAI221_X1 _500_ (
    .A(_049_),
    .B1(_053_),
    .B2(\totalcoeffs[0] ),
    .C1(_069_),
    .C2(\totalcoeffs[1] ),
    .ZN(_070_)
  );
  AOI221_X1 _501_ (
    .A(\trailingones[1] ),
    .B1(_200_),
    .B2(_070_),
    .C1(_060_),
    .C2(_127_),
    .ZN(_071_)
  );
  AOI221_X1 _502_ (
    .A(_149_),
    .B1(_265_),
    .B2(_067_),
    .C1(_068_),
    .C2(\ctable[1] ),
    .ZN(_072_)
  );
  NOR3_X1 _503_ (
    .A1(\totalcoeffs[4] ),
    .A2(_071_),
    .A3(_072_),
    .ZN(_073_)
  );
  AOI21_X1 _504_ (
    .A(_073_),
    .B1(_043_),
    .B2(_190_),
    .ZN(_074_)
  );
  NOR2_X1 _505_ (
    .A1(\ctable[0] ),
    .A2(\ctable[1] ),
    .ZN(_075_)
  );
  NAND2_X1 _506_ (
    .A1(_127_),
    .A2(_200_),
    .ZN(_076_)
  );
  NAND3_X1 _507_ (
    .A1(_200_),
    .A2(_222_),
    .A3(_323_),
    .ZN(_077_)
  );
  NOR3_X1 _508_ (
    .A1(\totalcoeffs[2] ),
    .A2(_322_),
    .A3(_331_),
    .ZN(_078_)
  );
  NOR2_X1 _509_ (
    .A1(_159_),
    .A2(_295_),
    .ZN(_079_)
  );
  OAI33_X1 _510_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[2] ),
    .A3(_009_),
    .B1(_078_),
    .B2(_079_),
    .B3(\trailingones[0] ),
    .ZN(_080_)
  );
  AOI22_X1 _511_ (
    .A1(_300_),
    .A2(_302_),
    .B1(_080_),
    .B2(\ctable[2] ),
    .ZN(_081_)
  );
  OAI22_X1 _512_ (
    .A1(\ctable[2] ),
    .A2(_074_),
    .B1(_077_),
    .B2(_081_),
    .ZN(\coeff_token[1] )
  );
  AOI211_X1 _513_ (
    .A(_200_),
    .B(_058_),
    .C1(_315_),
    .C2(\totalcoeffs[1] ),
    .ZN(_082_)
  );
  NAND2_X1 _514_ (
    .A1(\trailingones[0] ),
    .A2(_299_),
    .ZN(_083_)
  );
  AOI21_X1 _515_ (
    .A(_082_),
    .B1(_008_),
    .B2(\totalcoeffs[2] ),
    .ZN(_084_)
  );
  AOI21_X1 _516_ (
    .A(_190_),
    .B1(_083_),
    .B2(_084_),
    .ZN(_085_)
  );
  NOR2_X1 _517_ (
    .A1(_200_),
    .A2(_330_),
    .ZN(_086_)
  );
  OAI21_X1 _518_ (
    .A(_328_),
    .B1(_330_),
    .B2(_200_),
    .ZN(_087_)
  );
  NOR3_X1 _519_ (
    .A1(\totalcoeffs[2] ),
    .A2(\totalcoeffs[3] ),
    .A3(\trailingones[0] ),
    .ZN(_088_)
  );
  AOI221_X1 _520_ (
    .A(_085_),
    .B1(_087_),
    .B2(_044_),
    .C1(_088_),
    .C2(_326_),
    .ZN(_089_)
  );
  NAND2_X1 _521_ (
    .A1(\trailingones[1] ),
    .A2(\trailingones[0] ),
    .ZN(_090_)
  );
  XNOR2_X1 _522_ (
    .A(\trailingones[1] ),
    .B(\trailingones[0] ),
    .ZN(_091_)
  );
  XOR2_X1 _523_ (
    .A(\trailingones[1] ),
    .B(\trailingones[0] ),
    .Z(_092_)
  );
  NAND2_X1 _524_ (
    .A1(\ctable[0] ),
    .A2(_056_),
    .ZN(_093_)
  );
  OAI22_X1 _525_ (
    .A1(\ctable[0] ),
    .A2(_315_),
    .B1(_092_),
    .B2(_093_),
    .ZN(_094_)
  );
  AOI21_X1 _526_ (
    .A(_127_),
    .B1(_179_),
    .B2(\totalcoeffs[3] ),
    .ZN(_095_)
  );
  OAI33_X1 _527_ (
    .A1(\totalcoeffs[1] ),
    .A2(_292_),
    .A3(_090_),
    .B1(_095_),
    .B2(_333_),
    .B3(\trailingones[1] ),
    .ZN(_096_)
  );
  AND2_X1 _528_ (
    .A1(\totalcoeffs[0] ),
    .A2(_096_),
    .ZN(_097_)
  );
  AOI21_X1 _529_ (
    .A(_001_),
    .B1(_091_),
    .B2(_301_),
    .ZN(_098_)
  );
  AOI211_X1 _530_ (
    .A(_097_),
    .B(_098_),
    .C1(_317_),
    .C2(_094_),
    .ZN(_099_)
  );
  OAI22_X1 _531_ (
    .A1(_047_),
    .A2(_089_),
    .B1(_099_),
    .B2(\ctable[1] ),
    .ZN(_100_)
  );
  NOR2_X1 _532_ (
    .A1(\ctable[0] ),
    .A2(_200_),
    .ZN(_101_)
  );
  NAND3_X1 _533_ (
    .A1(\ctable[1] ),
    .A2(_323_),
    .A3(_058_),
    .ZN(_102_)
  );
  OAI211_X1 _534_ (
    .A(_127_),
    .B(_343_),
    .C1(_211_),
    .C2(\totalcoeffs[3] ),
    .ZN(_103_)
  );
  NAND2_X1 _535_ (
    .A1(_127_),
    .A2(\totalcoeffs[2] ),
    .ZN(_104_)
  );
  OAI211_X1 _536_ (
    .A(\totalcoeffs[1] ),
    .B(_103_),
    .C1(_066_),
    .C2(_044_),
    .ZN(_105_)
  );
  AOI21_X1 _537_ (
    .A(\trailingones[1] ),
    .B1(_102_),
    .B2(_105_),
    .ZN(_106_)
  );
  AOI211_X1 _538_ (
    .A(_127_),
    .B(_053_),
    .C1(\totalcoeffs[1] ),
    .C2(_159_),
    .ZN(_107_)
  );
  OAI21_X1 _539_ (
    .A(_107_),
    .B1(_009_),
    .B2(\ctable[1] ),
    .ZN(_108_)
  );
  NAND2_X1 _540_ (
    .A1(\ctable[1] ),
    .A2(_211_),
    .ZN(_109_)
  );
  NOR4_X1 _541_ (
    .A1(\totalcoeffs[3] ),
    .A2(_200_),
    .A3(\trailingones[0] ),
    .A4(_308_),
    .ZN(_110_)
  );
  OAI22_X1 _542_ (
    .A1(_149_),
    .A2(\totalcoeffs[3] ),
    .B1(_317_),
    .B2(_038_),
    .ZN(_111_)
  );
  OAI211_X1 _543_ (
    .A(_149_),
    .B(_109_),
    .C1(_200_),
    .C2(\totalcoeffs[1] ),
    .ZN(_112_)
  );
  AOI21_X1 _544_ (
    .A(_110_),
    .B1(_051_),
    .B2(_330_),
    .ZN(_113_)
  );
  OAI211_X1 _545_ (
    .A(_108_),
    .B(_113_),
    .C1(_111_),
    .C2(\ctable[1] ),
    .ZN(_114_)
  );
  AOI211_X1 _546_ (
    .A(_106_),
    .B(_114_),
    .C1(_112_),
    .C2(_063_),
    .ZN(_115_)
  );
  OAI21_X1 _547_ (
    .A(\totalcoeffs[4] ),
    .B1(_293_),
    .B2(\totalcoeffs[1] ),
    .ZN(_116_)
  );
  AOI21_X1 _548_ (
    .A(\ctable[0] ),
    .B1(_090_),
    .B2(_109_),
    .ZN(_117_)
  );
  NOR2_X1 _549_ (
    .A1(\totalcoeffs[3] ),
    .A2(_222_),
    .ZN(_118_)
  );
  NAND3_X1 _550_ (
    .A1(_179_),
    .A2(\totalcoeffs[4] ),
    .A3(_292_),
    .ZN(_119_)
  );
  OAI22_X1 _551_ (
    .A1(\totalcoeffs[4] ),
    .A2(_115_),
    .B1(_117_),
    .B2(_119_),
    .ZN(_120_)
  );
  AOI22_X1 _552_ (
    .A1(_222_),
    .A2(_100_),
    .B1(_120_),
    .B2(_168_),
    .ZN(_121_)
  );
  NAND3_X1 _553_ (
    .A1(\ctable[2] ),
    .A2(\trailingones[1] ),
    .A3(\trailingones[0] ),
    .ZN(_122_)
  );
  AOI21_X1 _554_ (
    .A(_329_),
    .B1(_122_),
    .B2(\totalcoeffs[0] ),
    .ZN(_123_)
  );
  AOI21_X1 _555_ (
    .A(_123_),
    .B1(_058_),
    .B2(_331_),
    .ZN(_124_)
  );
  NAND3_X1 _556_ (
    .A1(_222_),
    .A2(_292_),
    .A3(_075_),
    .ZN(_125_)
  );
  OAI22_X1 _557_ (
    .A1(\ctable[2] ),
    .A2(_121_),
    .B1(_124_),
    .B2(_125_),
    .ZN(\coeff_token[2] )
  );
  OAI21_X1 _558_ (
    .A(_254_),
    .B1(_076_),
    .B2(_090_),
    .ZN(_126_)
  );
  NAND3_X1 _559_ (
    .A1(\totalcoeffs[4] ),
    .A2(_292_),
    .A3(_126_),
    .ZN(_128_)
  );
  AOI22_X1 _560_ (
    .A1(_149_),
    .A2(\totalcoeffs[3] ),
    .B1(\ctable[1] ),
    .B2(_293_),
    .ZN(_129_)
  );
  OAI21_X1 _561_ (
    .A(_128_),
    .B1(_129_),
    .B2(\totalcoeffs[4] ),
    .ZN(_130_)
  );
  MUX2_X1 _562_ (
    .A(_344_),
    .B(_052_),
    .S(\totalcoeffs[2] ),
    .Z(_131_)
  );
  NOR2_X1 _563_ (
    .A1(\ctable[0] ),
    .A2(_190_),
    .ZN(_132_)
  );
  OAI22_X1 _564_ (
    .A1(\ctable[0] ),
    .A2(_190_),
    .B1(\ctable[1] ),
    .B2(_051_),
    .ZN(_133_)
  );
  AOI21_X1 _565_ (
    .A(_063_),
    .B1(_037_),
    .B2(_332_),
    .ZN(_134_)
  );
  OAI211_X1 _566_ (
    .A(_133_),
    .B(_134_),
    .C1(\trailingones[1] ),
    .C2(_131_),
    .ZN(_135_)
  );
  NOR2_X1 _567_ (
    .A1(\ctable[1] ),
    .A2(_037_),
    .ZN(_136_)
  );
  AOI211_X1 _568_ (
    .A(\ctable[1] ),
    .B(_037_),
    .C1(_344_),
    .C2(_308_),
    .ZN(_137_)
  );
  NOR3_X1 _569_ (
    .A1(\ctable[0] ),
    .A2(_289_),
    .A3(_009_),
    .ZN(_139_)
  );
  OAI21_X1 _570_ (
    .A(_306_),
    .B1(\trailingones[0] ),
    .B2(\ctable[1] ),
    .ZN(_140_)
  );
  AOI221_X1 _571_ (
    .A(_139_),
    .B1(_140_),
    .B2(_063_),
    .C1(_137_),
    .C2(\totalcoeffs[3] ),
    .ZN(_141_)
  );
  NOR2_X1 _572_ (
    .A1(\ctable[1] ),
    .A2(_004_),
    .ZN(_142_)
  );
  OAI211_X1 _573_ (
    .A(_293_),
    .B(_330_),
    .C1(_101_),
    .C2(_142_),
    .ZN(_143_)
  );
  OAI21_X1 _574_ (
    .A(_003_),
    .B1(_289_),
    .B2(\ctable[0] ),
    .ZN(_144_)
  );
  NAND2_X1 _575_ (
    .A1(_058_),
    .A2(_144_),
    .ZN(_145_)
  );
  NAND3_X1 _576_ (
    .A1(_141_),
    .A2(_143_),
    .A3(_145_),
    .ZN(_146_)
  );
  OAI21_X1 _577_ (
    .A(_062_),
    .B1(_324_),
    .B2(_200_),
    .ZN(_147_)
  );
  NAND2_X1 _578_ (
    .A1(\totalcoeffs[2] ),
    .A2(_101_),
    .ZN(_148_)
  );
  OAI21_X1 _579_ (
    .A(\totalcoeffs[2] ),
    .B1(_008_),
    .B2(_037_),
    .ZN(_150_)
  );
  NAND3_X1 _580_ (
    .A1(_190_),
    .A2(_109_),
    .A3(_150_),
    .ZN(_151_)
  );
  NAND4_X1 _581_ (
    .A1(\totalcoeffs[1] ),
    .A2(_254_),
    .A3(_275_),
    .A4(_151_),
    .ZN(_152_)
  );
  AOI221_X1 _582_ (
    .A(_146_),
    .B1(_147_),
    .B2(_331_),
    .C1(_135_),
    .C2(_322_),
    .ZN(_153_)
  );
  OR2_X1 _583_ (
    .A1(\totalcoeffs[4] ),
    .A2(_153_),
    .ZN(_154_)
  );
  AOI211_X1 _584_ (
    .A(\totalcoeffs[0] ),
    .B(\totalcoeffs[4] ),
    .C1(_148_),
    .C2(_152_),
    .ZN(_155_)
  );
  AOI21_X1 _585_ (
    .A(_155_),
    .B1(_130_),
    .B2(_295_),
    .ZN(_156_)
  );
  AOI21_X1 _586_ (
    .A(\ctable[2] ),
    .B1(_154_),
    .B2(_156_),
    .ZN(\coeff_token[3] )
  );
  NAND2_X1 _587_ (
    .A1(_222_),
    .A2(_079_),
    .ZN(_157_)
  );
  NOR2_X1 _588_ (
    .A1(_190_),
    .A2(\totalcoeffs[4] ),
    .ZN(_158_)
  );
  OAI211_X1 _589_ (
    .A(_159_),
    .B(_295_),
    .C1(_118_),
    .C2(_158_),
    .ZN(_160_)
  );
  AOI211_X1 _590_ (
    .A(\ctable[2] ),
    .B(_254_),
    .C1(_157_),
    .C2(_160_),
    .ZN(\coeff_token[4] )
  );
  NAND2_X1 _591_ (
    .A1(_345_),
    .A2(_158_),
    .ZN(_161_)
  );
  NAND3_X1 _592_ (
    .A1(\totalcoeffs[4] ),
    .A2(_292_),
    .A3(_295_),
    .ZN(_162_)
  );
  AOI211_X1 _593_ (
    .A(\ctable[2] ),
    .B(_254_),
    .C1(_161_),
    .C2(_162_),
    .ZN(\coeff_token[5] )
  );
  NOR2_X1 _594_ (
    .A1(_138_),
    .A2(\trailingones[1] ),
    .ZN(_163_)
  );
  OAI21_X1 _595_ (
    .A(\trailingones[0] ),
    .B1(\trailingones[1] ),
    .B2(_138_),
    .ZN(_164_)
  );
  AOI22_X1 _596_ (
    .A1(\totalcoeffs[1] ),
    .A2(_013_),
    .B1(_164_),
    .B2(_298_),
    .ZN(_165_)
  );
  NOR2_X1 _597_ (
    .A1(\totalcoeffs[2] ),
    .A2(_330_),
    .ZN(_166_)
  );
  NAND4_X1 _598_ (
    .A1(\ctable[2] ),
    .A2(_327_),
    .A3(_091_),
    .A4(_166_),
    .ZN(_167_)
  );
  OAI21_X1 _599_ (
    .A(_167_),
    .B1(_165_),
    .B2(\totalcoeffs[0] ),
    .ZN(_169_)
  );
  NAND4_X1 _600_ (
    .A1(_149_),
    .A2(\totalcoeffs[1] ),
    .A3(_340_),
    .A4(_047_),
    .ZN(_170_)
  );
  NAND2_X1 _601_ (
    .A1(\totalcoeffs[1] ),
    .A2(_038_),
    .ZN(_171_)
  );
  OAI221_X1 _602_ (
    .A(_170_),
    .B1(_171_),
    .B2(_302_),
    .C1(_346_),
    .C2(_046_),
    .ZN(_172_)
  );
  NOR2_X1 _603_ (
    .A1(\totalcoeffs[0] ),
    .A2(\ctable[1] ),
    .ZN(_173_)
  );
  AOI21_X1 _604_ (
    .A(_173_),
    .B1(\totalcoeffs[1] ),
    .B2(\totalcoeffs[2] ),
    .ZN(_174_)
  );
  OR3_X1 _605_ (
    .A1(_326_),
    .A2(_058_),
    .A3(_174_),
    .ZN(_175_)
  );
  OR2_X1 _606_ (
    .A1(\totalcoeffs[1] ),
    .A2(_008_),
    .ZN(_176_)
  );
  NAND3_X1 _607_ (
    .A1(\totalcoeffs[0] ),
    .A2(_328_),
    .A3(_176_),
    .ZN(_177_)
  );
  AOI21_X1 _608_ (
    .A(\ctable[0] ),
    .B1(_175_),
    .B2(_177_),
    .ZN(_178_)
  );
  OAI21_X1 _609_ (
    .A(\totalcoeffs[3] ),
    .B1(_172_),
    .B2(_178_),
    .ZN(_180_)
  );
  AOI21_X1 _610_ (
    .A(\ctable[1] ),
    .B1(\totalcoeffs[2] ),
    .B2(_127_),
    .ZN(_181_)
  );
  OAI22_X1 _611_ (
    .A1(_342_),
    .A2(_061_),
    .B1(_181_),
    .B2(_327_),
    .ZN(_182_)
  );
  AOI211_X1 _612_ (
    .A(_014_),
    .B(_173_),
    .C1(_047_),
    .C2(\trailingones[0] ),
    .ZN(_183_)
  );
  AOI21_X1 _613_ (
    .A(_183_),
    .B1(_055_),
    .B2(_314_),
    .ZN(_184_)
  );
  OAI22_X1 _614_ (
    .A1(_159_),
    .A2(_008_),
    .B1(_026_),
    .B2(_149_),
    .ZN(_185_)
  );
  AOI22_X1 _615_ (
    .A1(_211_),
    .A2(_182_),
    .B1(_185_),
    .B2(\ctable[1] ),
    .ZN(_186_)
  );
  MUX2_X1 _616_ (
    .A(_184_),
    .B(_186_),
    .S(\totalcoeffs[1] ),
    .Z(_187_)
  );
  AND2_X1 _617_ (
    .A1(_180_),
    .A2(_187_),
    .ZN(_188_)
  );
  AOI22_X1 _618_ (
    .A1(\ctable[0] ),
    .A2(_309_),
    .B1(_065_),
    .B2(_233_),
    .ZN(_189_)
  );
  AOI211_X1 _619_ (
    .A(_200_),
    .B(_092_),
    .C1(_343_),
    .C2(_333_),
    .ZN(_191_)
  );
  OAI22_X1 _620_ (
    .A1(\trailingones[0] ),
    .A2(_301_),
    .B1(_327_),
    .B2(_159_),
    .ZN(_192_)
  );
  AOI21_X1 _621_ (
    .A(_191_),
    .B1(_192_),
    .B2(\ctable[0] ),
    .ZN(_193_)
  );
  NAND3_X1 _622_ (
    .A1(\trailingones[0] ),
    .A2(_302_),
    .A3(_306_),
    .ZN(_194_)
  );
  OAI211_X1 _623_ (
    .A(_193_),
    .B(_194_),
    .C1(_026_),
    .C2(_189_),
    .ZN(_195_)
  );
  AOI22_X1 _624_ (
    .A1(_075_),
    .A2(_169_),
    .B1(_195_),
    .B2(_138_),
    .ZN(_196_)
  );
  OAI22_X1 _625_ (
    .A1(\ctable[2] ),
    .A2(_188_),
    .B1(_196_),
    .B2(\totalcoeffs[3] ),
    .ZN(_197_)
  );
  AOI21_X1 _626_ (
    .A(\ctable[2] ),
    .B1(_254_),
    .B2(_162_),
    .ZN(_198_)
  );
  AOI21_X1 _627_ (
    .A(_198_),
    .B1(_197_),
    .B2(_222_),
    .ZN(\ctoken_len[0] )
  );
  NAND2_X1 _628_ (
    .A1(_090_),
    .A2(_142_),
    .ZN(_199_)
  );
  NAND2_X1 _629_ (
    .A1(_233_),
    .A2(_050_),
    .ZN(_201_)
  );
  NAND2_X1 _630_ (
    .A1(\totalcoeffs[3] ),
    .A2(_090_),
    .ZN(_202_)
  );
  AOI211_X1 _631_ (
    .A(_159_),
    .B(\ctable[1] ),
    .C1(_026_),
    .C2(_202_),
    .ZN(_203_)
  );
  OAI221_X1 _632_ (
    .A(_201_),
    .B1(_018_),
    .B2(_014_),
    .C1(_001_),
    .C2(_090_),
    .ZN(_204_)
  );
  OAI21_X1 _633_ (
    .A(_109_),
    .B1(_056_),
    .B2(_003_),
    .ZN(_205_)
  );
  OAI21_X1 _634_ (
    .A(_346_),
    .B1(_211_),
    .B2(\totalcoeffs[3] ),
    .ZN(_206_)
  );
  AOI22_X1 _635_ (
    .A1(\trailingones[1] ),
    .A2(_205_),
    .B1(_206_),
    .B2(\totalcoeffs[0] ),
    .ZN(_207_)
  );
  OAI21_X1 _636_ (
    .A(\totalcoeffs[1] ),
    .B1(_203_),
    .B2(_204_),
    .ZN(_208_)
  );
  NOR4_X1 _637_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[2] ),
    .A3(_190_),
    .A4(_109_),
    .ZN(_209_)
  );
  OAI221_X1 _638_ (
    .A(\totalcoeffs[2] ),
    .B1(\ctable[1] ),
    .B2(_050_),
    .C1(\trailingones[0] ),
    .C2(\trailingones[1] ),
    .ZN(_210_)
  );
  MUX2_X1 _639_ (
    .A(_333_),
    .B(_018_),
    .S(\totalcoeffs[0] ),
    .Z(_212_)
  );
  OAI21_X1 _640_ (
    .A(_210_),
    .B1(_212_),
    .B2(\trailingones[1] ),
    .ZN(_213_)
  );
  NAND3_X1 _641_ (
    .A1(_168_),
    .A2(\ctable[1] ),
    .A3(_091_),
    .ZN(_214_)
  );
  NAND2_X1 _642_ (
    .A1(_033_),
    .A2(_090_),
    .ZN(_215_)
  );
  OAI21_X1 _643_ (
    .A(_214_),
    .B1(_215_),
    .B2(_331_),
    .ZN(_216_)
  );
  AOI21_X1 _644_ (
    .A(_213_),
    .B1(_216_),
    .B2(\totalcoeffs[3] ),
    .ZN(_217_)
  );
  OAI221_X1 _645_ (
    .A(_208_),
    .B1(_217_),
    .B2(\totalcoeffs[1] ),
    .C1(_012_),
    .C2(_207_),
    .ZN(_218_)
  );
  OAI211_X1 _646_ (
    .A(_127_),
    .B(_138_),
    .C1(_209_),
    .C2(_218_),
    .ZN(_219_)
  );
  AOI22_X1 _647_ (
    .A1(_302_),
    .A2(_092_),
    .B1(_163_),
    .B2(_045_),
    .ZN(_220_)
  );
  NOR4_X1 _648_ (
    .A1(\totalcoeffs[1] ),
    .A2(\ctable[1] ),
    .A3(_324_),
    .A4(_220_),
    .ZN(_221_)
  );
  AOI21_X1 _649_ (
    .A(\totalcoeffs[2] ),
    .B1(\totalcoeffs[0] ),
    .B2(\totalcoeffs[3] ),
    .ZN(_223_)
  );
  OAI21_X1 _650_ (
    .A(_004_),
    .B1(_092_),
    .B2(_223_),
    .ZN(_224_)
  );
  NOR3_X1 _651_ (
    .A1(\trailingones[1] ),
    .A2(_159_),
    .A3(_168_),
    .ZN(_225_)
  );
  AOI22_X1 _652_ (
    .A1(\ctable[0] ),
    .A2(_224_),
    .B1(_225_),
    .B2(_051_),
    .ZN(_226_)
  );
  NAND4_X1 _653_ (
    .A1(\totalcoeffs[0] ),
    .A2(\trailingones[0] ),
    .A3(_315_),
    .A4(_014_),
    .ZN(_227_)
  );
  OR3_X1 _654_ (
    .A1(\trailingones[1] ),
    .A2(\totalcoeffs[0] ),
    .A3(_344_),
    .ZN(_228_)
  );
  OAI211_X1 _655_ (
    .A(_227_),
    .B(_228_),
    .C1(_275_),
    .C2(_315_),
    .ZN(_229_)
  );
  NOR3_X1 _656_ (
    .A1(_149_),
    .A2(_344_),
    .A3(_004_),
    .ZN(_230_)
  );
  NOR3_X1 _657_ (
    .A1(_332_),
    .A2(_339_),
    .A3(_013_),
    .ZN(_231_)
  );
  AOI21_X1 _658_ (
    .A(_231_),
    .B1(_066_),
    .B2(_299_),
    .ZN(_232_)
  );
  AOI221_X1 _659_ (
    .A(_230_),
    .B1(_232_),
    .B2(\totalcoeffs[1] ),
    .C1(_317_),
    .C2(_229_),
    .ZN(_234_)
  );
  OAI21_X1 _660_ (
    .A(_234_),
    .B1(_226_),
    .B2(\totalcoeffs[1] ),
    .ZN(_235_)
  );
  NOR2_X1 _661_ (
    .A1(\ctable[2] ),
    .A2(\ctable[1] ),
    .ZN(_236_)
  );
  AOI21_X1 _662_ (
    .A(_221_),
    .B1(_235_),
    .B2(_236_),
    .ZN(_237_)
  );
  AOI21_X1 _663_ (
    .A(\totalcoeffs[4] ),
    .B1(_219_),
    .B2(_237_),
    .ZN(_238_)
  );
  NOR3_X1 _664_ (
    .A1(\ctable[0] ),
    .A2(\ctable[2] ),
    .A3(_162_),
    .ZN(_239_)
  );
  AOI21_X1 _665_ (
    .A(_238_),
    .B1(_239_),
    .B2(_200_),
    .ZN(\ctoken_len[1] )
  );
  AOI21_X1 _666_ (
    .A(_086_),
    .B1(_176_),
    .B2(\totalcoeffs[2] ),
    .ZN(_240_)
  );
  OAI21_X1 _667_ (
    .A(\totalcoeffs[2] ),
    .B1(\ctable[1] ),
    .B2(_338_),
    .ZN(_241_)
  );
  NAND3_X1 _668_ (
    .A1(\ctable[1] ),
    .A2(_090_),
    .A3(_176_),
    .ZN(_242_)
  );
  OAI211_X1 _669_ (
    .A(_241_),
    .B(_242_),
    .C1(_168_),
    .C2(_240_),
    .ZN(_244_)
  );
  OAI211_X1 _670_ (
    .A(\totalcoeffs[1] ),
    .B(_004_),
    .C1(\trailingones[0] ),
    .C2(_190_),
    .ZN(_245_)
  );
  AOI21_X1 _671_ (
    .A(_245_),
    .B1(_104_),
    .B2(_066_),
    .ZN(_246_)
  );
  AOI211_X1 _672_ (
    .A(\totalcoeffs[1] ),
    .B(_190_),
    .C1(\ctable[0] ),
    .C2(_168_),
    .ZN(_247_)
  );
  AOI21_X1 _673_ (
    .A(_246_),
    .B1(_247_),
    .B2(_044_),
    .ZN(_248_)
  );
  AOI21_X1 _674_ (
    .A(_318_),
    .B1(_056_),
    .B2(_127_),
    .ZN(_249_)
  );
  NOR3_X1 _675_ (
    .A1(\totalcoeffs[1] ),
    .A2(_324_),
    .A3(_026_),
    .ZN(_250_)
  );
  AOI21_X1 _676_ (
    .A(_250_),
    .B1(_249_),
    .B2(_066_),
    .ZN(_251_)
  );
  AOI21_X1 _677_ (
    .A(_323_),
    .B1(_179_),
    .B2(\ctable[0] ),
    .ZN(_252_)
  );
  AOI21_X1 _678_ (
    .A(_252_),
    .B1(_190_),
    .B2(_168_),
    .ZN(_253_)
  );
  AOI21_X1 _679_ (
    .A(\trailingones[1] ),
    .B1(_044_),
    .B2(_253_),
    .ZN(_255_)
  );
  OAI22_X1 _680_ (
    .A1(\totalcoeffs[3] ),
    .A2(_308_),
    .B1(_061_),
    .B2(_301_),
    .ZN(_256_)
  );
  NAND2_X1 _681_ (
    .A1(_168_),
    .A2(_256_),
    .ZN(_257_)
  );
  OAI211_X1 _682_ (
    .A(_159_),
    .B(_301_),
    .C1(\totalcoeffs[3] ),
    .C2(_149_),
    .ZN(_258_)
  );
  AOI21_X1 _683_ (
    .A(_326_),
    .B1(_179_),
    .B2(_127_),
    .ZN(_259_)
  );
  OAI221_X1 _684_ (
    .A(_257_),
    .B1(_258_),
    .B2(_252_),
    .C1(_259_),
    .C2(_001_),
    .ZN(_260_)
  );
  AOI221_X1 _685_ (
    .A(\ctable[1] ),
    .B1(_251_),
    .B2(_255_),
    .C1(_248_),
    .C2(\trailingones[1] ),
    .ZN(_261_)
  );
  AOI221_X1 _686_ (
    .A(_261_),
    .B1(_244_),
    .B2(_132_),
    .C1(_336_),
    .C2(_260_),
    .ZN(_262_)
  );
  AOI21_X1 _687_ (
    .A(\totalcoeffs[0] ),
    .B1(_333_),
    .B2(_343_),
    .ZN(_263_)
  );
  NOR2_X1 _688_ (
    .A1(_045_),
    .A2(_263_),
    .ZN(_264_)
  );
  OAI22_X1 _689_ (
    .A1(_315_),
    .A2(_340_),
    .B1(_264_),
    .B2(\trailingones[1] ),
    .ZN(_266_)
  );
  NAND3_X1 _690_ (
    .A1(_323_),
    .A2(_054_),
    .A3(_266_),
    .ZN(_267_)
  );
  OAI21_X1 _691_ (
    .A(_267_),
    .B1(_262_),
    .B2(\ctable[2] ),
    .ZN(_268_)
  );
  NOR4_X1 _692_ (
    .A1(\totalcoeffs[0] ),
    .A2(_308_),
    .A3(_333_),
    .A4(_077_),
    .ZN(_269_)
  );
  AOI211_X1 _693_ (
    .A(_239_),
    .B(_269_),
    .C1(_268_),
    .C2(_222_),
    .ZN(\ctoken_len[2] )
  );
  AND2_X1 _694_ (
    .A1(_190_),
    .A2(_306_),
    .ZN(_270_)
  );
  AOI21_X1 _695_ (
    .A(\totalcoeffs[2] ),
    .B1(\totalcoeffs[3] ),
    .B2(_346_),
    .ZN(_271_)
  );
  OAI21_X1 _696_ (
    .A(_271_),
    .B1(_270_),
    .B2(_055_),
    .ZN(_272_)
  );
  AOI21_X1 _697_ (
    .A(\ctable[1] ),
    .B1(\trailingones[0] ),
    .B2(_037_),
    .ZN(_273_)
  );
  OAI221_X1 _698_ (
    .A(_272_),
    .B1(_273_),
    .B2(\totalcoeffs[3] ),
    .C1(_199_),
    .C2(\ctable[0] ),
    .ZN(_274_)
  );
  OAI211_X1 _699_ (
    .A(\totalcoeffs[3] ),
    .B(_346_),
    .C1(_056_),
    .C2(_136_),
    .ZN(_276_)
  );
  AOI21_X1 _700_ (
    .A(\totalcoeffs[2] ),
    .B1(_076_),
    .B2(_118_),
    .ZN(_277_)
  );
  AOI211_X1 _701_ (
    .A(_001_),
    .B(_008_),
    .C1(_090_),
    .C2(_127_),
    .ZN(_278_)
  );
  AOI221_X1 _702_ (
    .A(_278_),
    .B1(_277_),
    .B2(_276_),
    .C1(\totalcoeffs[0] ),
    .C2(_292_),
    .ZN(_279_)
  );
  NOR3_X1 _703_ (
    .A1(\ctable[1] ),
    .A2(_004_),
    .A3(_047_),
    .ZN(_280_)
  );
  OAI21_X1 _704_ (
    .A(_176_),
    .B1(_280_),
    .B2(\ctable[2] ),
    .ZN(_281_)
  );
  OAI21_X1 _705_ (
    .A(\ctable[2] ),
    .B1(\totalcoeffs[0] ),
    .B2(_001_),
    .ZN(_282_)
  );
  OAI21_X1 _706_ (
    .A(\ctable[1] ),
    .B1(_000_),
    .B2(\ctable[0] ),
    .ZN(_283_)
  );
  AND4_X1 _707_ (
    .A1(_116_),
    .A2(_281_),
    .A3(_282_),
    .A4(_283_),
    .ZN(_284_)
  );
  OAI21_X1 _708_ (
    .A(_284_),
    .B1(_279_),
    .B2(\totalcoeffs[1] ),
    .ZN(_285_)
  );
  AOI21_X1 _709_ (
    .A(_285_),
    .B1(_274_),
    .B2(\totalcoeffs[1] ),
    .ZN(\ctoken_len[3] )
  );
  AOI211_X1 _710_ (
    .A(_295_),
    .B(_330_),
    .C1(_329_),
    .C2(\trailingones[0] ),
    .ZN(_287_)
  );
  NAND3_X1 _711_ (
    .A1(\totalcoeffs[2] ),
    .A2(_158_),
    .A3(_287_),
    .ZN(_288_)
  );
  AOI211_X1 _712_ (
    .A(\ctable[2] ),
    .B(_076_),
    .C1(_162_),
    .C2(_288_),
    .ZN(\ctoken_len[4] )
  );
endmodule
