/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module axi_dwidth_converter_v2_1_b_downsizer(ARESET, ACLK, cmd_valid, cmd_split, cmd_repeat, cmd_ready, cmd_id, S_AXI_BID, S_AXI_BRESP, S_AXI_BVALID, S_AXI_BREADY, M_AXI_BRESP, M_AXI_BVALID, M_AXI_BREADY);
  wire [1:0] _000_;
  wire _001_;
  wire [7:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  input ACLK;
  input ARESET;
  output M_AXI_BREADY;
  wire M_AXI_BREADY_I;
  input [1:0] M_AXI_BRESP;
  input M_AXI_BVALID;
  output S_AXI_BID;
  wire S_AXI_BID_I;
  input S_AXI_BREADY;
  wire S_AXI_BREADY_I;
  output [1:0] S_AXI_BRESP;
  wire [1:0] S_AXI_BRESP_ACC;
  wire [1:0] S_AXI_BRESP_I;
  output S_AXI_BVALID;
  wire S_AXI_BVALID_I;
  input cmd_id;
  output cmd_ready;
  wire cmd_ready_i;
  input [7:0] cmd_repeat;
  input cmd_split;
  input cmd_valid;
  wire first_mi_word;
  wire [7:0] repeat_cnt;
  INV_X1 _063_ (
    .A(repeat_cnt[2]),
    .ZN(_010_)
  );
  INV_X1 _064_ (
    .A(repeat_cnt[4]),
    .ZN(_011_)
  );
  INV_X1 _065_ (
    .A(repeat_cnt[5]),
    .ZN(_012_)
  );
  INV_X1 _066_ (
    .A(repeat_cnt[6]),
    .ZN(_013_)
  );
  INV_X1 _067_ (
    .A(first_mi_word),
    .ZN(_014_)
  );
  INV_X1 _068_ (
    .A(S_AXI_BRESP_ACC[0]),
    .ZN(_015_)
  );
  INV_X1 _069_ (
    .A(S_AXI_BRESP_ACC[1]),
    .ZN(_016_)
  );
  INV_X1 _070_ (
    .A(M_AXI_BVALID),
    .ZN(_017_)
  );
  NOR2_X1 _071_ (
    .A1(repeat_cnt[6]),
    .A2(repeat_cnt[7]),
    .ZN(_018_)
  );
  NOR2_X1 _072_ (
    .A1(repeat_cnt[0]),
    .A2(repeat_cnt[1]),
    .ZN(_019_)
  );
  NOR4_X1 _073_ (
    .A1(repeat_cnt[2]),
    .A2(repeat_cnt[3]),
    .A3(repeat_cnt[4]),
    .A4(repeat_cnt[5]),
    .ZN(_020_)
  );
  NAND4_X1 _074_ (
    .A1(_003_),
    .A2(_018_),
    .A3(_019_),
    .A4(_020_),
    .ZN(_021_)
  );
  AOI21_X1 _075_ (
    .A(S_AXI_BREADY),
    .B1(_021_),
    .B2(cmd_split),
    .ZN(_022_)
  );
  INV_X1 _076_ (
    .A(_022_),
    .ZN(M_AXI_BREADY)
  );
  NOR2_X1 _077_ (
    .A1(_017_),
    .A2(_022_),
    .ZN(_023_)
  );
  NAND2_X1 _078_ (
    .A1(M_AXI_BVALID),
    .A2(M_AXI_BREADY),
    .ZN(_024_)
  );
  MUX2_X1 _079_ (
    .A(repeat_cnt[0]),
    .B(cmd_repeat[0]),
    .S(first_mi_word),
    .Z(_025_)
  );
  AOI21_X1 _080_ (
    .A(repeat_cnt[0]),
    .B1(M_AXI_BVALID),
    .B2(M_AXI_BREADY),
    .ZN(_026_)
  );
  AOI211_X1 _081_ (
    .A(ARESET),
    .B(_026_),
    .C1(_025_),
    .C2(_023_),
    .ZN(_002_[0])
  );
  MUX2_X1 _082_ (
    .A(repeat_cnt[1]),
    .B(cmd_repeat[1]),
    .S(first_mi_word),
    .Z(_027_)
  );
  NOR2_X1 _083_ (
    .A1(_025_),
    .A2(_027_),
    .ZN(_028_)
  );
  XOR2_X1 _084_ (
    .A(_025_),
    .B(_027_),
    .Z(_029_)
  );
  AOI21_X1 _085_ (
    .A(repeat_cnt[1]),
    .B1(M_AXI_BVALID),
    .B2(M_AXI_BREADY),
    .ZN(_030_)
  );
  AOI211_X1 _086_ (
    .A(ARESET),
    .B(_030_),
    .C1(_029_),
    .C2(_023_),
    .ZN(_002_[1])
  );
  MUX2_X1 _087_ (
    .A(repeat_cnt[2]),
    .B(cmd_repeat[2]),
    .S(first_mi_word),
    .Z(_031_)
  );
  NOR3_X1 _088_ (
    .A1(_025_),
    .A2(_027_),
    .A3(_031_),
    .ZN(_032_)
  );
  XOR2_X1 _089_ (
    .A(_028_),
    .B(_031_),
    .Z(_033_)
  );
  NOR3_X1 _090_ (
    .A1(_017_),
    .A2(_022_),
    .A3(_033_),
    .ZN(_034_)
  );
  AOI211_X1 _091_ (
    .A(ARESET),
    .B(_034_),
    .C1(_024_),
    .C2(_010_),
    .ZN(_002_[2])
  );
  MUX2_X1 _092_ (
    .A(repeat_cnt[3]),
    .B(cmd_repeat[3]),
    .S(first_mi_word),
    .Z(_035_)
  );
  OR4_X1 _093_ (
    .A1(_025_),
    .A2(_027_),
    .A3(_031_),
    .A4(_035_),
    .ZN(_036_)
  );
  XNOR2_X1 _094_ (
    .A(_032_),
    .B(_035_),
    .ZN(_037_)
  );
  AOI21_X1 _095_ (
    .A(repeat_cnt[3]),
    .B1(M_AXI_BVALID),
    .B2(M_AXI_BREADY),
    .ZN(_038_)
  );
  AOI211_X1 _096_ (
    .A(ARESET),
    .B(_038_),
    .C1(_037_),
    .C2(_023_),
    .ZN(_002_[3])
  );
  MUX2_X1 _097_ (
    .A(repeat_cnt[4]),
    .B(cmd_repeat[4]),
    .S(first_mi_word),
    .Z(_039_)
  );
  XNOR2_X1 _098_ (
    .A(_036_),
    .B(_039_),
    .ZN(_040_)
  );
  NOR3_X1 _099_ (
    .A1(_017_),
    .A2(_022_),
    .A3(_040_),
    .ZN(_041_)
  );
  AOI211_X1 _100_ (
    .A(ARESET),
    .B(_041_),
    .C1(_024_),
    .C2(_011_),
    .ZN(_002_[4])
  );
  MUX2_X1 _101_ (
    .A(repeat_cnt[5]),
    .B(cmd_repeat[5]),
    .S(first_mi_word),
    .Z(_042_)
  );
  OAI21_X1 _102_ (
    .A(_042_),
    .B1(_039_),
    .B2(_036_),
    .ZN(_043_)
  );
  OR3_X1 _103_ (
    .A1(_036_),
    .A2(_039_),
    .A3(_042_),
    .ZN(_044_)
  );
  AND3_X1 _104_ (
    .A1(M_AXI_BVALID),
    .A2(M_AXI_BREADY),
    .A3(_044_),
    .ZN(_045_)
  );
  AOI221_X1 _105_ (
    .A(ARESET),
    .B1(_043_),
    .B2(_045_),
    .C1(_024_),
    .C2(_012_),
    .ZN(_002_[5])
  );
  MUX2_X1 _106_ (
    .A(repeat_cnt[6]),
    .B(cmd_repeat[6]),
    .S(first_mi_word),
    .Z(_046_)
  );
  NAND2_X1 _107_ (
    .A1(_044_),
    .A2(_046_),
    .ZN(_047_)
  );
  NOR4_X1 _108_ (
    .A1(_036_),
    .A2(_039_),
    .A3(_042_),
    .A4(_046_),
    .ZN(_048_)
  );
  NOR3_X1 _109_ (
    .A1(_017_),
    .A2(_022_),
    .A3(_048_),
    .ZN(_049_)
  );
  AOI221_X1 _110_ (
    .A(ARESET),
    .B1(_047_),
    .B2(_049_),
    .C1(_024_),
    .C2(_013_),
    .ZN(_002_[6])
  );
  MUX2_X1 _111_ (
    .A(repeat_cnt[7]),
    .B(cmd_repeat[7]),
    .S(first_mi_word),
    .Z(_050_)
  );
  XNOR2_X1 _112_ (
    .A(_048_),
    .B(_050_),
    .ZN(_051_)
  );
  AOI21_X1 _113_ (
    .A(repeat_cnt[7]),
    .B1(M_AXI_BVALID),
    .B2(M_AXI_BREADY),
    .ZN(_052_)
  );
  AOI211_X1 _114_ (
    .A(ARESET),
    .B(_052_),
    .C1(_051_),
    .C2(_023_),
    .ZN(_002_[7])
  );
  NOR2_X1 _115_ (
    .A1(M_AXI_BRESP[1]),
    .A2(_005_),
    .ZN(_053_)
  );
  AOI22_X1 _116_ (
    .A1(M_AXI_BRESP[0]),
    .A2(_004_),
    .B1(_005_),
    .B2(M_AXI_BRESP[1]),
    .ZN(_054_)
  );
  OAI211_X1 _117_ (
    .A(_014_),
    .B(cmd_split),
    .C1(_053_),
    .C2(_054_),
    .ZN(_006_)
  );
  MUX2_X1 _118_ (
    .A(S_AXI_BRESP_ACC[0]),
    .B(M_AXI_BRESP[0]),
    .S(_006_),
    .Z(S_AXI_BRESP[0])
  );
  NOR3_X1 _119_ (
    .A1(_017_),
    .A2(_022_),
    .A3(S_AXI_BRESP[0]),
    .ZN(_007_)
  );
  AOI211_X1 _120_ (
    .A(ARESET),
    .B(_007_),
    .C1(_024_),
    .C2(_015_),
    .ZN(_000_[0])
  );
  MUX2_X1 _121_ (
    .A(S_AXI_BRESP_ACC[1]),
    .B(M_AXI_BRESP[1]),
    .S(_006_),
    .Z(S_AXI_BRESP[1])
  );
  NOR3_X1 _122_ (
    .A1(_017_),
    .A2(_022_),
    .A3(S_AXI_BRESP[1]),
    .ZN(_008_)
  );
  AOI211_X1 _123_ (
    .A(ARESET),
    .B(_008_),
    .C1(_024_),
    .C2(_016_),
    .ZN(_000_[1])
  );
  AOI21_X1 _124_ (
    .A(_017_),
    .B1(_021_),
    .B2(cmd_split),
    .ZN(S_AXI_BVALID)
  );
  AND3_X1 _125_ (
    .A1(S_AXI_BREADY),
    .A2(cmd_valid),
    .A3(S_AXI_BVALID),
    .ZN(cmd_ready)
  );
  AOI21_X1 _126_ (
    .A(ARESET),
    .B1(S_AXI_BREADY),
    .B2(S_AXI_BVALID),
    .ZN(_009_)
  );
  OAI21_X1 _127_ (
    .A(_009_),
    .B1(_023_),
    .B2(_014_),
    .ZN(_001_)
  );
  DFF_X1 _128_ (
    .CK(ACLK),
    .D(_002_[0]),
    .Q(repeat_cnt[0]),
    .QN(_055_)
  );
  DFF_X1 _129_ (
    .CK(ACLK),
    .D(_002_[1]),
    .Q(repeat_cnt[1]),
    .QN(_056_)
  );
  DFF_X1 _130_ (
    .CK(ACLK),
    .D(_002_[2]),
    .Q(repeat_cnt[2]),
    .QN(_057_)
  );
  DFF_X1 _131_ (
    .CK(ACLK),
    .D(_002_[3]),
    .Q(repeat_cnt[3]),
    .QN(_058_)
  );
  DFF_X1 _132_ (
    .CK(ACLK),
    .D(_002_[4]),
    .Q(repeat_cnt[4]),
    .QN(_059_)
  );
  DFF_X1 _133_ (
    .CK(ACLK),
    .D(_002_[5]),
    .Q(repeat_cnt[5]),
    .QN(_060_)
  );
  DFF_X1 _134_ (
    .CK(ACLK),
    .D(_002_[6]),
    .Q(repeat_cnt[6]),
    .QN(_061_)
  );
  DFF_X1 _135_ (
    .CK(ACLK),
    .D(_002_[7]),
    .Q(repeat_cnt[7]),
    .QN(_062_)
  );
  DFF_X1 _136_ (
    .CK(ACLK),
    .D(_001_),
    .Q(first_mi_word),
    .QN(_003_)
  );
  DFF_X1 _137_ (
    .CK(ACLK),
    .D(_000_[0]),
    .Q(S_AXI_BRESP_ACC[0]),
    .QN(_004_)
  );
  DFF_X1 _138_ (
    .CK(ACLK),
    .D(_000_[1]),
    .Q(S_AXI_BRESP_ACC[1]),
    .QN(_005_)
  );
  assign M_AXI_BREADY_I = M_AXI_BREADY;
  assign S_AXI_BID = cmd_id;
  assign S_AXI_BID_I = cmd_id;
  assign S_AXI_BREADY_I = S_AXI_BREADY;
  assign S_AXI_BRESP_I = S_AXI_BRESP;
  assign S_AXI_BVALID_I = S_AXI_BVALID;
  assign cmd_ready_i = cmd_ready;
endmodule
